package GUI;

import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import model.MYSQL;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Cleaning_schedule extends javax.swing.JFrame {

    /**
     * Creates new form Cleaning_schedule
     */
    public Cleaning_schedule() {
        initComponents();
        loadSchedule();
        loadstaff();
        loadroomnumber();
       

    }

    public void loadSchedule() {
        try {
            // Search user table from database
            ResultSet resultSet = MYSQL.execute("SELECT * FROM cleaning_scheadule INNER JOIN `role` ON  `cleaning_scheadule`.`role_id` = `role`.`role_id`");

            // Load data to table
            DefaultTableModel model = (DefaultTableModel) jTableSchedule.getModel();
            model.setRowCount(0);

            // Get data to table
            while (resultSet.next()) {
                Vector vector1 = new Vector();

                vector1.add(resultSet.getString("date"));
                vector1.add(resultSet.getString("room_id"));
                vector1.add(resultSet.getString("role.name"));
                vector1.add(resultSet.getString("note"));
                model.addRow(vector1);
            }

            // Set model after adding all rows
            jTableSchedule.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void loadstaff()  {
        
         try {

            Vector vector = new Vector();//vector object
            ResultSet resultset = MYSQL.execute("SELECT `name` FROM `role` ");

            while (resultset.next()) {
                 vector.add("SELECT ROLE");
                String name = resultset.getString("name");
                //System.out.println(mobile); 
                vector.add(name);
            }

            DefaultComboBoxModel comboboxModel = new DefaultComboBoxModel(vector);
            jComboBoxStaff.setModel(comboboxModel);

        } catch (Exception e) {
        }
        
    }
    
    public void loadroomnumber()  {
        
         try {

            Vector vector = new Vector();//vector object
            ResultSet resultset = MYSQL.execute("SELECT `room_id` FROM `room` ");

            while (resultset.next()) {
                
                vector.add("SELECT ROOM NUMBER");
                String room_id = resultset.getString("room_id");
                //System.out.println(mobile); 
                vector.add(room_id);
            }
           

            DefaultComboBoxModel comboboxModel = new DefaultComboBoxModel(vector);
            jComboBox1.setModel(comboboxModel);

        } catch (Exception e) {
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelRomStatus = new javax.swing.JLabel();
        jLabelLogOut = new javax.swing.JLabel();
        jLabelInventory = new javax.swing.JLabel();
        jLabelMaintanence = new javax.swing.JLabel();
        jPanelCurrent = new javax.swing.JPanel();
        jLabelCleaning = new javax.swing.JLabel();
        jPaneluser = new javax.swing.JPanel();
        jLabelUseImg = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelUserId = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelSearch = new javax.swing.JLabel();
        jScrollPaneTableSupliers1 = new javax.swing.JScrollPane();
        jTableSchedule = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabelUserId1 = new javax.swing.JLabel();
        jLabelUserId3 = new javax.swing.JLabel();
        jComboBoxStaff = new javax.swing.JComboBox<>();
        jLabelUserId5 = new javax.swing.JLabel();
        jButtonInsert2 = new javax.swing.JButton();
        jButtonUpdate2 = new javax.swing.JButton();
        jButtonDelete2 = new javax.swing.JButton();
        jLabelUserId4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNotes = new javax.swing.JTextArea();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBoxIrotyScearch = new javax.swing.JComboBox<>();
        jButtonClearNic1 = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(83, 66, 54));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 500));

        jLabel1.setBackground(new java.awt.Color(83, 66, 54));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N

        jLabelRomStatus.setBackground(new java.awt.Color(83, 66, 54));
        jLabelRomStatus.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabelRomStatus.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRomStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRomStatus.setText("Room Status");
        jLabelRomStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRomStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRomStatusMouseClicked(evt);
            }
        });

        jLabelLogOut.setBackground(new java.awt.Color(83, 66, 54));
        jLabelLogOut.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabelLogOut.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogOut.setText("Log Out");
        jLabelLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLogOut.setPreferredSize(null);

        jLabelInventory.setBackground(new java.awt.Color(83, 66, 54));
        jLabelInventory.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabelInventory.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInventory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInventory.setText("Inventory Request");
        jLabelInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInventoryMouseClicked(evt);
            }
        });

        jLabelMaintanence.setBackground(new java.awt.Color(83, 66, 54));
        jLabelMaintanence.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabelMaintanence.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMaintanence.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMaintanence.setText("Maintenance Request");
        jLabelMaintanence.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanelCurrent.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCurrent.setPreferredSize(new java.awt.Dimension(199, 32));

        jLabelCleaning.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCleaning.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabelCleaning.setForeground(new java.awt.Color(83, 66, 54));
        jLabelCleaning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCleaning.setText("Cleaning Schedule");
        jLabelCleaning.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCleaning.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCleaningMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelCurrentLayout = new javax.swing.GroupLayout(jPanelCurrent);
        jPanelCurrent.setLayout(jPanelCurrentLayout);
        jPanelCurrentLayout.setHorizontalGroup(
            jPanelCurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
            .addGroup(jPanelCurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCurrentLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelCleaning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelCurrentLayout.setVerticalGroup(
            jPanelCurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelCurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCurrentLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jLabelCleaning, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPaneluser.setBackground(new java.awt.Color(83, 66, 54));
        jPaneluser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPaneluser.setPreferredSize(new java.awt.Dimension(199, 72));

        jLabelUseImg.setBackground(new java.awt.Color(83, 66, 54));
        jLabelUseImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/user.png"))); // NOI18N

        jLabelId.setBackground(new java.awt.Color(83, 66, 54));
        jLabelId.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabelId.setForeground(new java.awt.Color(255, 255, 255));
        jLabelId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelId.setText("ID     : ");
        jLabelId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelUserName.setBackground(new java.awt.Color(83, 66, 54));
        jLabelUserName.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabelUserName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserName.setText("Shehara");
        jLabelUserName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelUserId.setBackground(new java.awt.Color(83, 66, 54));
        jLabelUserId.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabelUserId.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserId.setText("RS0001");
        jLabelUserId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelName.setBackground(new java.awt.Color(83, 66, 54));
        jLabelName.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelName.setText("Name:");
        jLabelName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPaneluserLayout = new javax.swing.GroupLayout(jPaneluser);
        jPaneluser.setLayout(jPaneluserLayout);
        jPaneluserLayout.setHorizontalGroup(
            jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneluserLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabelUseImg)
                .addGap(10, 10, 10)
                .addGroup(jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneluserLayout.createSequentialGroup()
                        .addComponent(jLabelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUserId))
                    .addGroup(jPaneluserLayout.createSequentialGroup()
                        .addComponent(jLabelName)
                        .addGap(3, 3, 3)
                        .addComponent(jLabelUserName)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPaneluserLayout.setVerticalGroup(
            jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneluserLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUseImg)
                    .addGroup(jPaneluserLayout.createSequentialGroup()
                        .addGroup(jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUserId))
                        .addGap(4, 4, 4)
                        .addGroup(jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelName)
                            .addComponent(jLabelUserName)))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addComponent(jPanelCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPaneluser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelInventory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelLogOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelRomStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelMaintanence, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanelCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabelRomStatus)
                .addGap(18, 18, 18)
                .addComponent(jLabelMaintanence, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabelInventory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabelLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPaneluser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabelSearch.setBackground(new java.awt.Color(83, 66, 54));
        jLabelSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.png"))); // NOI18N

        jScrollPaneTableSupliers1.setBackground(new java.awt.Color(83, 66, 54));
        jScrollPaneTableSupliers1.setAutoscrolls(true);
        jScrollPaneTableSupliers1.setPreferredSize(new java.awt.Dimension(269, 189));

        jTableSchedule.setAutoCreateRowSorter(true);
        jTableSchedule.setBackground(new java.awt.Color(199, 189, 177));
        jTableSchedule.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableSchedule.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTableSchedule.setForeground(new java.awt.Color(83, 66, 54));
        jTableSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Room number", "Assigne staff", "Notes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSchedule.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableSchedule.setGridColor(new java.awt.Color(255, 255, 255));
        jTableSchedule.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTableSchedule.setSelectionForeground(new java.awt.Color(155, 117, 1));
        jTableSchedule.getTableHeader().setReorderingAllowed(false);
        jScrollPaneTableSupliers1.setViewportView(jTableSchedule);

        jPanel3.setBackground(new java.awt.Color(221, 217, 214));

        jLabelUserId1.setBackground(new java.awt.Color(221, 217, 214));
        jLabelUserId1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelUserId1.setForeground(new java.awt.Color(83, 66, 54));
        jLabelUserId1.setText("Date:");

        jLabelUserId3.setBackground(new java.awt.Color(221, 217, 214));
        jLabelUserId3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelUserId3.setForeground(new java.awt.Color(83, 66, 54));
        jLabelUserId3.setText("Room number:");

        jComboBoxStaff.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jComboBoxStaff.setForeground(new java.awt.Color(155, 117, 1));
        jComboBoxStaff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxStaff.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jComboBoxStaff.setPreferredSize(new java.awt.Dimension(155, 30));
        jComboBoxStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStaffActionPerformed(evt);
            }
        });

        jLabelUserId5.setBackground(new java.awt.Color(221, 217, 214));
        jLabelUserId5.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelUserId5.setForeground(new java.awt.Color(83, 66, 54));
        jLabelUserId5.setText("Notes");

        jButtonInsert2.setBackground(new java.awt.Color(155, 117, 1));
        jButtonInsert2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonInsert2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInsert2.setText("Insert");
        jButtonInsert2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jButtonInsert2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonInsert2.setFocusable(false);
        jButtonInsert2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonInsert2.setPreferredSize(new java.awt.Dimension(73, 30));
        jButtonInsert2.setSelected(true);
        jButtonInsert2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsert2ActionPerformed(evt);
            }
        });

        jButtonUpdate2.setBackground(new java.awt.Color(155, 117, 1));
        jButtonUpdate2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonUpdate2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate2.setText("Update");
        jButtonUpdate2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jButtonUpdate2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUpdate2.setFocusable(false);
        jButtonUpdate2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonUpdate2.setPreferredSize(new java.awt.Dimension(73, 30));
        jButtonUpdate2.setSelected(true);
        jButtonUpdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdate2ActionPerformed(evt);
            }
        });

        jButtonDelete2.setBackground(new java.awt.Color(155, 117, 1));
        jButtonDelete2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonDelete2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete2.setText("Delete");
        jButtonDelete2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jButtonDelete2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDelete2.setFocusable(false);
        jButtonDelete2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDelete2.setPreferredSize(new java.awt.Dimension(73, 30));
        jButtonDelete2.setSelected(true);
        jButtonDelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelete2ActionPerformed(evt);
            }
        });

        jLabelUserId4.setBackground(new java.awt.Color(221, 217, 214));
        jLabelUserId4.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelUserId4.setForeground(new java.awt.Color(83, 66, 54));
        jLabelUserId4.setText("Assigne staff");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaNotes.setColumns(20);
        jTextAreaNotes.setRows(5);
        jScrollPane1.setViewportView(jTextAreaNotes);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUserId4)
                    .addComponent(jLabelUserId5)
                    .addComponent(jLabelUserId1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUserId3)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDelete2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonUpdate2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonInsert2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxStaff, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabelUserId1)
                .addGap(8, 8, 8)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUserId3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUserId4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelUserId5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jButtonInsert2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUpdate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDelete2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jComboBoxIrotyScearch.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jComboBoxIrotyScearch.setForeground(new java.awt.Color(155, 117, 1));
        jComboBoxIrotyScearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxIrotyScearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jComboBoxIrotyScearch.setPreferredSize(new java.awt.Dimension(105, 30));
        jComboBoxIrotyScearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIrotyScearchActionPerformed(evt);
            }
        });

        jButtonClearNic1.setBackground(new java.awt.Color(155, 117, 1));
        jButtonClearNic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/clear.png"))); // NOI18N
        jButtonClearNic1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        jButtonClearNic1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClearNic1.setPreferredSize(new java.awt.Dimension(25, 25));
        jButtonClearNic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearNic1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelSearch)
                        .addGap(38, 38, 38)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxIrotyScearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jButtonClearNic1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneTableSupliers1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxIrotyScearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonClearNic1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelSearch)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPaneTableSupliers1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(816, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelRomStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRomStatusMouseClicked

    }//GEN-LAST:event_jLabelRomStatusMouseClicked

    private void jLabelCleaningMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCleaningMouseClicked

    }//GEN-LAST:event_jLabelCleaningMouseClicked

    private void jLabelInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInventoryMouseClicked

    }//GEN-LAST:event_jLabelInventoryMouseClicked

    private void jComboBoxStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStaffActionPerformed

    }//GEN-LAST:event_jComboBoxStaffActionPerformed

    private void jButtonInsert2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsert2ActionPerformed
     
        
       Date  date1 =  jDateChooser1.getDate();
      String roomnumber =jComboBox1.getSelectedItem().toString();
      String role = jComboBoxStaff.getSelectedItem().toString();
      String note = jTextAreaNotes.getText();
      
//        System.out.println(date1);
//        
//        PreparedStatement preparedStatement = connection.prepareStatement(date1);
//        
//        LocalDate localDate = LocalDate.of(date1); // Example date
//            preparedStatement.setDate(1, java.sql.Date.valueOf(localDate));
//            preparedStatement.setString(2, "hhhg");
//            preparedStatement.setInt(3, 1);

      
        try {
            MYSQL.execute("INSERT INTO `cleaning_scheadule` (`date`, `note`, `room_id`, `role_id`)VALUES ('"+date1+"','"+note+"', '"+roomnumber+"', (SELECT `role_id` FROM `role` WHERE `name` = '"+role+"')) ");
        } catch (Exception e) {
        }
      
      
      
      
      
      
      

//        try {
//
//            DefaultTableModel model = (DefaultTableModel) jTableSchedule.getModel();
//            model.setRowCount(0);
////ResultSet  resultset = MySQL1.search("SELECT * FROM user ORDER BY lname  ASC");
//            ResultSet resultset = MYSQL.execute("SELECT * FROM cleaning_scheadule INNER JOIN `role` ON  `cleaning_scheadule`.`role_id` = `role`.`role_id`");
//
//            while (resultset.next()) {
//                String dateString = resultset.getString("date");
//                String roomString = resultset.getString("room_id");
//                String roleString = resultset.getString("role.name");
//                String noteString = resultset.getString("note");
//
//                Vector vector = new Vector(); //ROW
//
//                vector.add(dateString);
//                vector.add(roomString);
//                vector.add(roleString);
//                vector.add(noteString);
//
//                model.addRow(vector);
//            }
//
////DefaultComboBoxModel  ComboBoxModel =  new DefaultComboBoxModel(vector);
////jComboBox1.setModel(ComboBoxModel);
//        } catch (Exception e) {
//            e.printStackTrace();
//
//        }

    }//GEN-LAST:event_jButtonInsert2ActionPerformed

    private void jButtonUpdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUpdate2ActionPerformed

    private void jButtonDelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelete2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDelete2ActionPerformed

    private void jComboBoxIrotyScearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIrotyScearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxIrotyScearchActionPerformed

    private void jButtonClearNic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearNic1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClearNic1ActionPerformed

    private void jDatePicker2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDatePicker2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDatePicker2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cleaning_schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cleaning_schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cleaning_schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cleaning_schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cleaning_schedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClearNic1;
    private javax.swing.JButton jButtonDelete2;
    private javax.swing.JButton jButtonInsert2;
    private javax.swing.JButton jButtonUpdate2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxIrotyScearch;
    private javax.swing.JComboBox<String> jComboBoxStaff;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCleaning;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelInventory;
    private javax.swing.JLabel jLabelLogOut;
    private javax.swing.JLabel jLabelMaintanence;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelRomStatus;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelUseImg;
    private javax.swing.JLabel jLabelUserId;
    private javax.swing.JLabel jLabelUserId1;
    private javax.swing.JLabel jLabelUserId3;
    private javax.swing.JLabel jLabelUserId4;
    private javax.swing.JLabel jLabelUserId5;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCurrent;
    private javax.swing.JPanel jPaneluser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneTableSupliers1;
    private javax.swing.JTable jTableSchedule;
    private javax.swing.JTextArea jTextAreaNotes;
    // End of variables declaration//GEN-END:variables
}
