/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Helitha
 */
public class CorporateAccount extends javax.swing.JFrame {

    /**
     * Creates new form CorporateAccount
     */
    public CorporateAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPaneluser = new javax.swing.JPanel();
        jLabelUseImg = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelUserId = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelSystemconfiguration = new javax.swing.JLabel();
        jLabelSystemconfiguration1 = new javax.swing.JLabel();
        jLabelLogsAudit = new javax.swing.JLabel();
        jLabelSystemconfiguration2 = new javax.swing.JLabel();
        jLabelLogOut = new javax.swing.JLabel();
        jLabelUserManagement = new javax.swing.JLabel();
        jPanelCurrent = new javax.swing.JPanel();
        jLabelDashboard = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(83, 66, 54));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 500));
        jPanel2.setRequestFocusEnabled(false);

        jPaneluser.setBackground(new java.awt.Color(83, 66, 54));
        jPaneluser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPaneluser.setPreferredSize(new java.awt.Dimension(199, 72));

        jLabelUseImg.setBackground(new java.awt.Color(83, 66, 54));
        jLabelUseImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/user.png"))); // NOI18N

        jLabelId.setBackground(new java.awt.Color(83, 66, 54));
        jLabelId.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabelId.setForeground(new java.awt.Color(255, 255, 255));
        jLabelId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelId.setText("ID     : ");
        jLabelId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelUserName.setBackground(new java.awt.Color(83, 66, 54));
        jLabelUserName.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabelUserName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserName.setText("Shehara");
        jLabelUserName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelUserId.setBackground(new java.awt.Color(83, 66, 54));
        jLabelUserId.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabelUserId.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserId.setText("RS0001");
        jLabelUserId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelName.setBackground(new java.awt.Color(83, 66, 54));
        jLabelName.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelName.setText("Name:");
        jLabelName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPaneluserLayout = new javax.swing.GroupLayout(jPaneluser);
        jPaneluser.setLayout(jPaneluserLayout);
        jPaneluserLayout.setHorizontalGroup(
            jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneluserLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabelUseImg)
                .addGap(10, 10, 10)
                .addGroup(jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneluserLayout.createSequentialGroup()
                        .addComponent(jLabelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUserId))
                    .addGroup(jPaneluserLayout.createSequentialGroup()
                        .addComponent(jLabelName)
                        .addGap(3, 3, 3)
                        .addComponent(jLabelUserName)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPaneluserLayout.setVerticalGroup(
            jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneluserLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUseImg)
                    .addGroup(jPaneluserLayout.createSequentialGroup()
                        .addGroup(jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUserId))
                        .addGap(4, 4, 4)
                        .addGroup(jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelName)
                            .addComponent(jLabelUserName)))))
        );

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N

        jLabelSystemconfiguration.setBackground(new java.awt.Color(83, 66, 54));
        jLabelSystemconfiguration.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelSystemconfiguration.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSystemconfiguration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSystemconfiguration.setText("Guest Feedback Analysis");
        jLabelSystemconfiguration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSystemconfiguration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSystemconfigurationMouseClicked(evt);
            }
        });

        jLabelSystemconfiguration1.setBackground(new java.awt.Color(83, 66, 54));
        jLabelSystemconfiguration1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelSystemconfiguration1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSystemconfiguration1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSystemconfiguration1.setText("Marketing Campaign");
        jLabelSystemconfiguration1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSystemconfiguration1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSystemconfiguration1MouseClicked(evt);
            }
        });

        jLabelLogsAudit.setBackground(new java.awt.Color(83, 66, 54));
        jLabelLogsAudit.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelLogsAudit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogsAudit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogsAudit.setText("Sales Lead Tracking");
        jLabelLogsAudit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLogsAudit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogsAuditMouseClicked(evt);
            }
        });

        jLabelSystemconfiguration2.setBackground(new java.awt.Color(83, 66, 54));
        jLabelSystemconfiguration2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelSystemconfiguration2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSystemconfiguration2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSystemconfiguration2.setText("Promotional Campaign");
        jLabelSystemconfiguration2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSystemconfiguration2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSystemconfiguration2MouseClicked(evt);
            }
        });

        jLabelLogOut.setBackground(new java.awt.Color(83, 66, 54));
        jLabelLogOut.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabelLogOut.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogOut.setText("Log Out");
        jLabelLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelUserManagement.setBackground(new java.awt.Color(83, 66, 54));
        jLabelUserManagement.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelUserManagement.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserManagement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserManagement.setText("Dashboard");
        jLabelUserManagement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelUserManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUserManagementMouseClicked(evt);
            }
        });

        jPanelCurrent.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCurrent.setPreferredSize(new java.awt.Dimension(199, 32));

        jLabelDashboard.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDashboard.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelDashboard.setForeground(new java.awt.Color(83, 66, 54));
        jLabelDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDashboard.setText("Corporate Account");
        jLabelDashboard.setToolTipText("");
        jLabelDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelCurrentLayout = new javax.swing.GroupLayout(jPanelCurrent);
        jPanelCurrent.setLayout(jPanelCurrentLayout);
        jPanelCurrentLayout.setHorizontalGroup(
            jPanelCurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
        );
        jPanelCurrentLayout.setVerticalGroup(
            jPanelCurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelLogo))
            .addComponent(jLabelUserManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabelLogsAudit, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabelSystemconfiguration1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabelSystemconfiguration, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabelSystemconfiguration2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabelLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPaneluser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabelLogo)
                .addGap(7, 7, 7)
                .addComponent(jLabelUserManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabelLogsAudit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabelSystemconfiguration1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabelSystemconfiguration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabelSystemconfiguration2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabelLogOut)
                .addGap(7, 7, 7)
                .addComponent(jPaneluser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(83, 66, 54));
        jLabel1.setText("Corporate Accounts");

        jPanel3.setBackground(new java.awt.Color(221, 217, 214));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(221, 217, 214), 1, true));

        jTextField1.setPreferredSize(new java.awt.Dimension(388, 22));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(83, 66, 54));
        jLabel2.setText("Email");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(83, 66, 54));
        jLabel3.setText("Customer Name");

        jTextField2.setPreferredSize(new java.awt.Dimension(388, 22));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(83, 66, 54));
        jLabel4.setText("Mobile");

        jTextField3.setPreferredSize(new java.awt.Dimension(388, 22));

        jButton2.setBackground(new java.awt.Color(83, 66, 54));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(83, 66, 54));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.setContentAreaFilled(false);
        jButton3.setOpaque(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(83, 66, 54));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("ADD");
        jButton4.setContentAreaFilled(false);
        jButton4.setOpaque(true);

        jTextField4.setPreferredSize(new java.awt.Dimension(388, 22));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(83, 66, 54));
        jLabel5.setText("Email");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15))
                        .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(3, 3, 3)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.png"))); // NOI18N

        jTextField5.setPreferredSize(new java.awt.Dimension(152, 25));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(522, 134));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Email", "Contact", "status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(818, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSystemconfigurationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSystemconfigurationMouseClicked
        GuestFeedbackAnalysis GuestFeedbackAnalysis = new GuestFeedbackAnalysis();// Get the new SystemConfiguration
        GuestFeedbackAnalysis.setVisible(true); // Show the new SystemConfiguration
        this.setVisible(false); // Close the current window
    }//GEN-LAST:event_jLabelSystemconfigurationMouseClicked

    private void jLabelSystemconfiguration1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSystemconfiguration1MouseClicked
        MarketingCampaign MarketingCampaign = new MarketingCampaign();// Get the new MarketingCampaign
        MarketingCampaign.setVisible(true); // Show the new MarketingCampaign
        this.setVisible(false); // Close the current window
    }//GEN-LAST:event_jLabelSystemconfiguration1MouseClicked

    private void jLabelLogsAuditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogsAuditMouseClicked
        SalesLeadTracking SalesLeadTracking = new SalesLeadTracking();// Get the new logs&audit
        SalesLeadTracking.setVisible(true); // Show the new logs&audit
        this.setVisible(false); // Close the current window
    }//GEN-LAST:event_jLabelLogsAuditMouseClicked

    private void jLabelSystemconfiguration2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSystemconfiguration2MouseClicked
        PromotionalCampaign PromotionalCampaign = new PromotionalCampaign();// Get the  PromotionalCampaign
        PromotionalCampaign.setVisible(true); // Show the new  PromotionalCampaign
        this.setVisible(false); // Close the current window
    }//GEN-LAST:event_jLabelSystemconfiguration2MouseClicked

    private void jLabelUserManagementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUserManagementMouseClicked
        Dashboard Dashboard = new Dashboard();// Get the Dashboard
        Dashboard.setVisible(true); // Show the new Dashboard
        this.setVisible(false); // Close the current window
    }//GEN-LAST:event_jLabelUserManagementMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CorporateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CorporateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CorporateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CorporateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CorporateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelDashboard;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelLogOut;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelLogsAudit;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelSystemconfiguration;
    private javax.swing.JLabel jLabelSystemconfiguration1;
    private javax.swing.JLabel jLabelSystemconfiguration2;
    private javax.swing.JLabel jLabelUseImg;
    private javax.swing.JLabel jLabelUserId;
    private javax.swing.JLabel jLabelUserManagement;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCurrent;
    private javax.swing.JPanel jPaneluser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
