package GUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Inventory extends javax.swing.JFrame {

    /**
     * Creates new form Inventory
     */
    public Inventory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelRomStatus = new javax.swing.JLabel();
        jLabelMaintanence = new javax.swing.JLabel();
        jLabelCleaning = new javax.swing.JLabel();
        jLabelLogOut = new javax.swing.JLabel();
        jPanelCurrent = new javax.swing.JPanel();
        jLabelInventory = new javax.swing.JLabel();
        jPaneluser = new javax.swing.JPanel();
        jLabelUseImg = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelUserId = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelUserId2 = new javax.swing.JLabel();
        jSpinnerRoomNo = new javax.swing.JSpinner();
        jLabelUserId3 = new javax.swing.JLabel();
        jComboBoxRoomType1 = new javax.swing.JComboBox<>();
        jLabelUserId5 = new javax.swing.JLabel();
        jButtonInsert2 = new javax.swing.JButton();
        jButtonUpdate2 = new javax.swing.JButton();
        jButtonDelete2 = new javax.swing.JButton();
        jLabelUserId4 = new javax.swing.JLabel();
        jComboBoxRoomType2 = new javax.swing.JComboBox<>();
        jScrollPaneDescription = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jComboBoxIrotyScearch = new javax.swing.JComboBox<>();
        jButtonClearNic1 = new javax.swing.JButton();
        jLabelSearch = new javax.swing.JLabel();
        jScrollPaneTableSupliers1 = new javax.swing.JScrollPane();
        jTableSupliers = new javax.swing.JTable();
        jComboBoxIrotyScearch1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(83, 66, 54));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 500));

        jLabel1.setBackground(new java.awt.Color(83, 66, 54));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N

        jLabelRomStatus.setBackground(new java.awt.Color(83, 66, 54));
        jLabelRomStatus.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelRomStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRomStatus.setText("Room Status");
        jLabelRomStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRomStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRomStatusMouseClicked(evt);
            }
        });

        jLabelMaintanence.setBackground(new java.awt.Color(83, 66, 54));
        jLabelMaintanence.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelMaintanence.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMaintanence.setText("Maintenance Request");
        jLabelMaintanence.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelCleaning.setBackground(new java.awt.Color(83, 66, 54));
        jLabelCleaning.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelCleaning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCleaning.setText("Cleaning Schedule");
        jLabelCleaning.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCleaning.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCleaningMouseClicked(evt);
            }
        });

        jLabelLogOut.setBackground(new java.awt.Color(83, 66, 54));
        jLabelLogOut.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabelLogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogOut.setText("Log Out");
        jLabelLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLogOut.setPreferredSize(null);

        jPanelCurrent.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCurrent.setPreferredSize(new java.awt.Dimension(199, 32));

        jLabelInventory.setBackground(new java.awt.Color(255, 255, 255));
        jLabelInventory.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelInventory.setForeground(new java.awt.Color(83, 66, 54));
        jLabelInventory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInventory.setText("Inventory Request");
        jLabelInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInventoryMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelCurrentLayout = new javax.swing.GroupLayout(jPanelCurrent);
        jPanelCurrent.setLayout(jPanelCurrentLayout);
        jPanelCurrentLayout.setHorizontalGroup(
            jPanelCurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
            .addGroup(jPanelCurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCurrentLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelCurrentLayout.setVerticalGroup(
            jPanelCurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
            .addGroup(jPanelCurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCurrentLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jLabelInventory, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPaneluser.setBackground(new java.awt.Color(83, 66, 54));
        jPaneluser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPaneluser.setPreferredSize(new java.awt.Dimension(199, 72));

        jLabelUseImg.setBackground(new java.awt.Color(83, 66, 54));
        jLabelUseImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/user.png"))); // NOI18N

        jLabelId.setBackground(new java.awt.Color(83, 66, 54));
        jLabelId.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabelId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelId.setText("ID     : ");
        jLabelId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelUserName.setBackground(new java.awt.Color(83, 66, 54));
        jLabelUserName.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabelUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserName.setText("Shehara");
        jLabelUserName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelUserId.setBackground(new java.awt.Color(83, 66, 54));
        jLabelUserId.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabelUserId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserId.setText("RS0001");
        jLabelUserId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelName.setBackground(new java.awt.Color(83, 66, 54));
        jLabelName.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelName.setText("Name:");
        jLabelName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPaneluserLayout = new javax.swing.GroupLayout(jPaneluser);
        jPaneluser.setLayout(jPaneluserLayout);
        jPaneluserLayout.setHorizontalGroup(
            jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneluserLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabelUseImg)
                .addGap(10, 10, 10)
                .addGroup(jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneluserLayout.createSequentialGroup()
                        .addComponent(jLabelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUserId))
                    .addGroup(jPaneluserLayout.createSequentialGroup()
                        .addComponent(jLabelName)
                        .addGap(3, 3, 3)
                        .addComponent(jLabelUserName)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPaneluserLayout.setVerticalGroup(
            jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneluserLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUseImg)
                    .addGroup(jPaneluserLayout.createSequentialGroup()
                        .addGroup(jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUserId))
                        .addGap(4, 4, 4)
                        .addGroup(jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelName)
                            .addComponent(jLabelUserName)))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addComponent(jPanelCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPaneluser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelCleaning, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelLogOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelRomStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelMaintanence, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabelCleaning, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelRomStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMaintanence, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jLabelLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPaneluser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(221, 217, 214));

        jLabelUserId2.setBackground(new java.awt.Color(221, 217, 214));
        jLabelUserId2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelUserId2.setForeground(new java.awt.Color(83, 66, 54));
        jLabelUserId2.setText("Item Name:");

        jSpinnerRoomNo.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jSpinnerRoomNo.setModel(new javax.swing.SpinnerNumberModel(100, 0, 100, 1));
        jSpinnerRoomNo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177)));
        jSpinnerRoomNo.setPreferredSize(new java.awt.Dimension(155, 30));

        jLabelUserId3.setBackground(new java.awt.Color(221, 217, 214));
        jLabelUserId3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelUserId3.setForeground(new java.awt.Color(83, 66, 54));
        jLabelUserId3.setText("Category");

        jComboBoxRoomType1.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jComboBoxRoomType1.setForeground(new java.awt.Color(155, 117, 1));
        jComboBoxRoomType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxRoomType1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jComboBoxRoomType1.setPreferredSize(new java.awt.Dimension(155, 30));
        jComboBoxRoomType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRoomType1ActionPerformed(evt);
            }
        });

        jLabelUserId5.setBackground(new java.awt.Color(221, 217, 214));
        jLabelUserId5.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelUserId5.setForeground(new java.awt.Color(83, 66, 54));
        jLabelUserId5.setText("Description");

        jButtonInsert2.setBackground(new java.awt.Color(155, 117, 1));
        jButtonInsert2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonInsert2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInsert2.setText("Insert");
        jButtonInsert2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jButtonInsert2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonInsert2.setFocusable(false);
        jButtonInsert2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonInsert2.setPreferredSize(new java.awt.Dimension(73, 30));
        jButtonInsert2.setSelected(true);
        jButtonInsert2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsert2ActionPerformed(evt);
            }
        });

        jButtonUpdate2.setBackground(new java.awt.Color(155, 117, 1));
        jButtonUpdate2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonUpdate2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate2.setText("Update");
        jButtonUpdate2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jButtonUpdate2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUpdate2.setFocusable(false);
        jButtonUpdate2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonUpdate2.setPreferredSize(new java.awt.Dimension(73, 30));
        jButtonUpdate2.setSelected(true);
        jButtonUpdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdate2ActionPerformed(evt);
            }
        });

        jButtonDelete2.setBackground(new java.awt.Color(155, 117, 1));
        jButtonDelete2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonDelete2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete2.setText("Delete");
        jButtonDelete2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jButtonDelete2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDelete2.setFocusable(false);
        jButtonDelete2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDelete2.setPreferredSize(new java.awt.Dimension(73, 30));
        jButtonDelete2.setSelected(true);
        jButtonDelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelete2ActionPerformed(evt);
            }
        });

        jLabelUserId4.setBackground(new java.awt.Color(221, 217, 214));
        jLabelUserId4.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelUserId4.setForeground(new java.awt.Color(83, 66, 54));
        jLabelUserId4.setText("Quantity:");

        jComboBoxRoomType2.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jComboBoxRoomType2.setForeground(new java.awt.Color(155, 117, 1));
        jComboBoxRoomType2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxRoomType2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jComboBoxRoomType2.setPreferredSize(new java.awt.Dimension(155, 30));
        jComboBoxRoomType2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRoomType2ActionPerformed(evt);
            }
        });

        jScrollPaneDescription.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPaneDescription.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jScrollPaneDescription.setToolTipText("");
        jScrollPaneDescription.setPreferredSize(new java.awt.Dimension(322, 60));
        jScrollPaneDescription.setRequestFocusEnabled(false);

        jTextAreaDescription.setColumns(1);
        jTextAreaDescription.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextAreaDescription.setForeground(new java.awt.Color(155, 117, 1));
        jTextAreaDescription.setLineWrap(true);
        jTextAreaDescription.setRows(3);
        jTextAreaDescription.setTabSize(15);
        jTextAreaDescription.setDisabledTextColor(new java.awt.Color(155, 117, 1));
        jTextAreaDescription.setPreferredSize(new java.awt.Dimension(2016, 60));
        jScrollPaneDescription.setViewportView(jTextAreaDescription);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelUserId3)
                        .addComponent(jComboBoxRoomType1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelUserId2)
                        .addComponent(jSpinnerRoomNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelUserId4)
                        .addComponent(jLabelUserId5)
                        .addComponent(jButtonUpdate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonInsert2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDelete2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jComboBoxRoomType2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelUserId3)
                .addGap(3, 3, 3)
                .addComponent(jComboBoxRoomType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabelUserId2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxRoomType2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelUserId4)
                .addGap(3, 3, 3)
                .addComponent(jSpinnerRoomNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabelUserId5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(53, 53, 53)
                .addComponent(jButtonInsert2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUpdate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDelete2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jComboBoxIrotyScearch.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jComboBoxIrotyScearch.setForeground(new java.awt.Color(155, 117, 1));
        jComboBoxIrotyScearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxIrotyScearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jComboBoxIrotyScearch.setPreferredSize(new java.awt.Dimension(105, 30));
        jComboBoxIrotyScearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIrotyScearchActionPerformed(evt);
            }
        });

        jButtonClearNic1.setBackground(new java.awt.Color(155, 117, 1));
        jButtonClearNic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/clear.png"))); // NOI18N
        jButtonClearNic1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        jButtonClearNic1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClearNic1.setPreferredSize(new java.awt.Dimension(25, 25));
        jButtonClearNic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearNic1ActionPerformed(evt);
            }
        });

        jLabelSearch.setBackground(new java.awt.Color(83, 66, 54));
        jLabelSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.png"))); // NOI18N

        jScrollPaneTableSupliers1.setBackground(new java.awt.Color(83, 66, 54));
        jScrollPaneTableSupliers1.setAutoscrolls(true);
        jScrollPaneTableSupliers1.setPreferredSize(new java.awt.Dimension(269, 189));

        jTableSupliers.setAutoCreateRowSorter(true);
        jTableSupliers.setBackground(new java.awt.Color(199, 189, 177));
        jTableSupliers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableSupliers.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTableSupliers.setForeground(new java.awt.Color(83, 66, 54));
        jTableSupliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Catogary", "Item Name", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSupliers.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableSupliers.setGridColor(new java.awt.Color(255, 255, 255));
        jTableSupliers.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTableSupliers.setSelectionForeground(new java.awt.Color(155, 117, 1));
        jTableSupliers.getTableHeader().setReorderingAllowed(false);
        jScrollPaneTableSupliers1.setViewportView(jTableSupliers);

        jComboBoxIrotyScearch1.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jComboBoxIrotyScearch1.setForeground(new java.awt.Color(155, 117, 1));
        jComboBoxIrotyScearch1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxIrotyScearch1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jComboBoxIrotyScearch1.setPreferredSize(new java.awt.Dimension(105, 30));
        jComboBoxIrotyScearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIrotyScearch1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxIrotyScearch1, 0, 108, Short.MAX_VALUE)
                        .addGap(76, 76, 76)
                        .addComponent(jComboBoxIrotyScearch, 0, 108, Short.MAX_VALUE)
                        .addGap(5, 5, 5)
                        .addComponent(jButtonClearNic1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneTableSupliers1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxIrotyScearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxIrotyScearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonClearNic1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPaneTableSupliers1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(816, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelRomStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRomStatusMouseClicked

    }//GEN-LAST:event_jLabelRomStatusMouseClicked

    private void jLabelCleaningMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCleaningMouseClicked

    }//GEN-LAST:event_jLabelCleaningMouseClicked

    private void jLabelInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInventoryMouseClicked

    }//GEN-LAST:event_jLabelInventoryMouseClicked

    private void jButtonDelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelete2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDelete2ActionPerformed

    private void jButtonUpdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUpdate2ActionPerformed

    private void jButtonInsert2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsert2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInsert2ActionPerformed

    private void jComboBoxRoomType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRoomType1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRoomType1ActionPerformed

    private void jComboBoxIrotyScearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIrotyScearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxIrotyScearchActionPerformed

    private void jButtonClearNic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearNic1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClearNic1ActionPerformed

    private void jComboBoxRoomType2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRoomType2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRoomType2ActionPerformed

    private void jComboBoxIrotyScearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIrotyScearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxIrotyScearch1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClearNic1;
    private javax.swing.JButton jButtonDelete2;
    private javax.swing.JButton jButtonInsert2;
    private javax.swing.JButton jButtonUpdate2;
    private javax.swing.JComboBox<String> jComboBoxIrotyScearch;
    private javax.swing.JComboBox<String> jComboBoxIrotyScearch1;
    private javax.swing.JComboBox<String> jComboBoxRoomType1;
    private javax.swing.JComboBox<String> jComboBoxRoomType2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCleaning;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelInventory;
    private javax.swing.JLabel jLabelLogOut;
    private javax.swing.JLabel jLabelMaintanence;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelRomStatus;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelUseImg;
    private javax.swing.JLabel jLabelUserId;
    private javax.swing.JLabel jLabelUserId2;
    private javax.swing.JLabel jLabelUserId3;
    private javax.swing.JLabel jLabelUserId4;
    private javax.swing.JLabel jLabelUserId5;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCurrent;
    private javax.swing.JPanel jPaneluser;
    private javax.swing.JScrollPane jScrollPaneDescription;
    private javax.swing.JScrollPane jScrollPaneTableSupliers1;
    private javax.swing.JSpinner jSpinnerRoomNo;
    private javax.swing.JTable jTableSupliers;
    private javax.swing.JTextArea jTextAreaDescription;
    // End of variables declaration//GEN-END:variables
}
