/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import static gui.UserDetails.roleMap;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.MYSQL;
import model.company;
import model.role;

/**
 *
 * @author DELL
 */
public class Supliers_companies extends javax.swing.JFrame {

    public static HashMap<String, company> companyMap = new HashMap();

    /**
     * Creates new form SupliersCompanies
     */
    public Supliers_companies() {
        initComponents();
        loadSuppliers();
        loadCompanies();
        company();
    }

    public void loadSuppliers() {
        try {
            // Search user table from database
            ResultSet resultSet = MYSQL.execute("SELECT * FROM `supplier`"
                    + "INNER JOIN `company` ON `supplier`.`company_id` = `company`.`company_id` ");

            // Load data to table
            DefaultTableModel model = (DefaultTableModel) jTableSupliers.getModel();
            model.setRowCount(0);

            // Get data to table
            while (resultSet.next()) {
                Vector<String> vector1 = new Vector<>();

                vector1.add(resultSet.getString("supplier_id"));
                vector1.add(resultSet.getString("sname"));
                vector1.add(resultSet.getString("company.name"));
                vector1.add(resultSet.getString("mobile"));
                model.addRow(vector1);
            }

            // Set model after adding all rows
            jTableSupliers.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void loadCompanies() {
        try {
            // Search user table from database
            ResultSet resultSet = MYSQL.execute("SELECT * FROM `company`");

            // Load data to table
            DefaultTableModel model = (DefaultTableModel) jTableCompany.getModel();
            model.setRowCount(0);

            // Get data to table
            while (resultSet.next()) {
                Vector<String> vector1 = new Vector<>();

                vector1.add(resultSet.getString("company_id"));
                vector1.add(resultSet.getString("name"));
                vector1.add(resultSet.getString("mobile"));
                vector1.add(resultSet.getString("adress"));

                model.addRow(vector1);
            }

            // Set model after adding all rows
            jTableCompany.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void company() {
        try {
            //search districts
            ResultSet resultSet = MYSQL.execute("SELECT * FROM `company`");

            Vector<String> vectorcompany = new Vector<>();
            vectorcompany.add("Select");

            while (resultSet.next()) {
                vectorcompany.add(resultSet.getString("name"));

                company company = new company();
                company.setCompany_id(resultSet.getInt("company_id"));
                company.setName(resultSet.getString("name"));

                companyMap.put(resultSet.getString("name"), company);
            }

            //set vector vector1 to district
            DefaultComboBoxModel model1 = new DefaultComboBoxModel(vectorcompany);
            jComboBox1.setModel(model1);

        } catch (Exception e) {
            e.printStackTrace();

        }
    }

    public void resetSupplier() {
        jTextFieldUserName.setText("");
        jTextFieldUserMobile1.setText("");
        jComboBox1.setSelectedItem("Select");
        jTextFieldUserId.setText("");
    }

    public void resetcompany() {
        jTextFieldCompanyName.setText("");
        jTextFieldCompanyMobile.setText("");
        jTextFieldAddress.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelScreen = new javax.swing.JPanel();
        jPanelSuplier = new javax.swing.JPanel();
        jLabelSupliers1 = new javax.swing.JLabel();
        jLabelUserId = new javax.swing.JLabel();
        jTextFieldUserId = new javax.swing.JTextField();
        jLabelUserName = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();
        jLabelUserCompany = new javax.swing.JLabel();
        jLabelUserMobile = new javax.swing.JLabel();
        jButtonInsert2 = new javax.swing.JButton();
        jButtonUpdate2 = new javax.swing.JButton();
        jButtonDelete2 = new javax.swing.JButton();
        jScrollPaneTableSupliers1 = new javax.swing.JScrollPane();
        jTableSupliers = new javax.swing.JTable();
        jTextFieldSearchSuplier = new javax.swing.JTextField();
        jButtonClearNic = new javax.swing.JButton();
        jLabelSearch = new javax.swing.JLabel();
        jTextFieldUserMobile1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanelCompany = new javax.swing.JPanel();
        jLabelCompanies = new javax.swing.JLabel();
        jLabelCompanyName = new javax.swing.JLabel();
        jTextFieldCompanyName = new javax.swing.JTextField();
        jLabelCompanyMobile = new javax.swing.JLabel();
        jTextFieldCompanyMobile = new javax.swing.JTextField();
        jLabelAddress = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jButtonInsert1 = new javax.swing.JButton();
        jButtonUpdate1 = new javax.swing.JButton();
        jButtonDelete1 = new javax.swing.JButton();
        jScrollPaneTableCompany = new javax.swing.JScrollPane();
        jTableCompany = new javax.swing.JTable();
        jTextFieldSearchCompany = new javax.swing.JTextField();
        jLabelSearch1 = new javax.swing.JLabel();
        jButtonClearCompanySearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanelScreen.setBackground(new java.awt.Color(255, 255, 255));

        jPanelSuplier.setBackground(new java.awt.Color(221, 217, 214));
        jPanelSuplier.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelSuplier.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabelSupliers1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSupliers1.setFont(new java.awt.Font("SansSerif", 3, 25)); // NOI18N
        jLabelSupliers1.setForeground(new java.awt.Color(83, 66, 54));
        jLabelSupliers1.setText("Supliers");
        jLabelSupliers1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(83, 66, 55)));
        jLabelSupliers1.setPreferredSize(new java.awt.Dimension(100, 34));

        jLabelUserId.setBackground(new java.awt.Color(221, 217, 214));
        jLabelUserId.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelUserId.setForeground(new java.awt.Color(83, 66, 54));
        jLabelUserId.setText("Id");

        jTextFieldUserId.setEditable(false);
        jTextFieldUserId.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextFieldUserId.setForeground(new java.awt.Color(155, 117, 1));
        jTextFieldUserId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jTextFieldUserId.setDoubleBuffered(true);
        jTextFieldUserId.setPreferredSize(new java.awt.Dimension(92, 25));
        jTextFieldUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserIdActionPerformed(evt);
            }
        });

        jLabelUserName.setBackground(new java.awt.Color(221, 217, 214));
        jLabelUserName.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelUserName.setForeground(new java.awt.Color(83, 66, 54));
        jLabelUserName.setText("Name:");

        jTextFieldUserName.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextFieldUserName.setForeground(new java.awt.Color(155, 117, 1));
        jTextFieldUserName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jTextFieldUserName.setDoubleBuffered(true);
        jTextFieldUserName.setPreferredSize(new java.awt.Dimension(352, 25));

        jLabelUserCompany.setBackground(new java.awt.Color(221, 217, 214));
        jLabelUserCompany.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelUserCompany.setForeground(new java.awt.Color(83, 66, 54));
        jLabelUserCompany.setText("Company:");

        jLabelUserMobile.setBackground(new java.awt.Color(221, 217, 214));
        jLabelUserMobile.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelUserMobile.setForeground(new java.awt.Color(83, 66, 54));
        jLabelUserMobile.setText("Mobile:");

        jButtonInsert2.setBackground(new java.awt.Color(155, 117, 1));
        jButtonInsert2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonInsert2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInsert2.setText("Insert");
        jButtonInsert2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jButtonInsert2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonInsert2.setFocusable(false);
        jButtonInsert2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonInsert2.setPreferredSize(new java.awt.Dimension(73, 30));
        jButtonInsert2.setSelected(true);
        jButtonInsert2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsert2ActionPerformed(evt);
            }
        });

        jButtonUpdate2.setBackground(new java.awt.Color(155, 117, 1));
        jButtonUpdate2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonUpdate2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate2.setText("Update");
        jButtonUpdate2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jButtonUpdate2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUpdate2.setFocusable(false);
        jButtonUpdate2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonUpdate2.setPreferredSize(new java.awt.Dimension(73, 30));
        jButtonUpdate2.setSelected(true);
        jButtonUpdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdate2ActionPerformed(evt);
            }
        });

        jButtonDelete2.setBackground(new java.awt.Color(155, 117, 1));
        jButtonDelete2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonDelete2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete2.setText("Delete");
        jButtonDelete2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jButtonDelete2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDelete2.setFocusable(false);
        jButtonDelete2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDelete2.setPreferredSize(new java.awt.Dimension(73, 30));
        jButtonDelete2.setSelected(true);
        jButtonDelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelete2ActionPerformed(evt);
            }
        });

        jScrollPaneTableSupliers1.setBackground(new java.awt.Color(83, 66, 54));
        jScrollPaneTableSupliers1.setAutoscrolls(true);
        jScrollPaneTableSupliers1.setPreferredSize(new java.awt.Dimension(269, 189));

        jTableSupliers.setAutoCreateRowSorter(true);
        jTableSupliers.setBackground(new java.awt.Color(199, 189, 177));
        jTableSupliers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableSupliers.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTableSupliers.setForeground(new java.awt.Color(83, 66, 54));
        jTableSupliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Name", "Company", "Mobile"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSupliers.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableSupliers.setGridColor(new java.awt.Color(255, 255, 255));
        jTableSupliers.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTableSupliers.setSelectionForeground(new java.awt.Color(155, 117, 1));
        jTableSupliers.getTableHeader().setReorderingAllowed(false);
        jTableSupliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableSupliersMouseReleased(evt);
            }
        });
        jScrollPaneTableSupliers1.setViewportView(jTableSupliers);

        jTextFieldSearchSuplier.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextFieldSearchSuplier.setForeground(new java.awt.Color(83, 66, 54));
        jTextFieldSearchSuplier.setText(" Search NIC");
        jTextFieldSearchSuplier.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(155, 117, 1)));
        jTextFieldSearchSuplier.setDisabledTextColor(new java.awt.Color(221, 217, 214));
        jTextFieldSearchSuplier.setPreferredSize(new java.awt.Dimension(129, 25));
        jTextFieldSearchSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchSuplierActionPerformed(evt);
            }
        });

        jButtonClearNic.setBackground(new java.awt.Color(155, 117, 1));
        jButtonClearNic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/clear.png"))); // NOI18N
        jButtonClearNic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        jButtonClearNic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClearNic.setPreferredSize(new java.awt.Dimension(25, 25));
        jButtonClearNic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearNicActionPerformed(evt);
            }
        });

        jLabelSearch.setBackground(new java.awt.Color(83, 66, 54));
        jLabelSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.png"))); // NOI18N

        jTextFieldUserMobile1.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextFieldUserMobile1.setForeground(new java.awt.Color(155, 117, 1));
        jTextFieldUserMobile1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jTextFieldUserMobile1.setDoubleBuffered(true);
        jTextFieldUserMobile1.setPreferredSize(new java.awt.Dimension(352, 25));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelSuplierLayout = new javax.swing.GroupLayout(jPanelSuplier);
        jPanelSuplier.setLayout(jPanelSuplierLayout);
        jPanelSuplierLayout.setHorizontalGroup(
            jPanelSuplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuplierLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelSuplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneTableSupliers1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .addGroup(jPanelSuplierLayout.createSequentialGroup()
                        .addGroup(jPanelSuplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelSuplierLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanelSuplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelUserCompany)
                                    .addComponent(jLabelUserId)
                                    .addComponent(jTextFieldUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanelSuplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSuplierLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelSuplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelSuplierLayout.createSequentialGroup()
                                        .addComponent(jLabelUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                        .addGap(53, 53, 53))
                                    .addComponent(jLabelUserMobile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                            .addGroup(jPanelSuplierLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jTextFieldUserMobile1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                    .addGroup(jPanelSuplierLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanelSuplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSuplierLayout.createSequentialGroup()
                                .addComponent(jLabelSupliers1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSuplierLayout.createSequentialGroup()
                                .addGroup(jPanelSuplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelSuplierLayout.createSequentialGroup()
                                        .addComponent(jLabelSearch)
                                        .addGap(0, 0, 0)
                                        .addComponent(jTextFieldSearchSuplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanelSuplierLayout.createSequentialGroup()
                                        .addComponent(jButtonInsert2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(15, 15, 15)
                                        .addComponent(jButtonUpdate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelSuplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonDelete2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanelSuplierLayout.createSequentialGroup()
                                        .addComponent(jButtonClearNic, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(22, 22, 22))
        );
        jPanelSuplierLayout.setVerticalGroup(
            jPanelSuplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuplierLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelSupliers1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSuplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUserId)
                    .addComponent(jLabelUserName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSuplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSuplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUserCompany)
                    .addComponent(jLabelUserMobile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSuplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUserMobile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanelSuplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInsert2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanelSuplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonClearNic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSearchSuplier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTableSupliers1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelCompany.setBackground(new java.awt.Color(221, 217, 214));
        jPanelCompany.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelCompany.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabelCompanies.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCompanies.setFont(new java.awt.Font("SansSerif", 3, 25)); // NOI18N
        jLabelCompanies.setForeground(new java.awt.Color(83, 66, 54));
        jLabelCompanies.setText("Companies");
        jLabelCompanies.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(83, 66, 55)));

        jLabelCompanyName.setBackground(new java.awt.Color(221, 217, 214));
        jLabelCompanyName.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelCompanyName.setForeground(new java.awt.Color(83, 66, 54));
        jLabelCompanyName.setText("Name:");

        jTextFieldCompanyName.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextFieldCompanyName.setForeground(new java.awt.Color(155, 117, 1));
        jTextFieldCompanyName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jTextFieldCompanyName.setDoubleBuffered(true);
        jTextFieldCompanyName.setPreferredSize(new java.awt.Dimension(123, 25));

        jLabelCompanyMobile.setBackground(new java.awt.Color(221, 217, 214));
        jLabelCompanyMobile.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelCompanyMobile.setForeground(new java.awt.Color(83, 66, 54));
        jLabelCompanyMobile.setText("Mobile:");

        jTextFieldCompanyMobile.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextFieldCompanyMobile.setForeground(new java.awt.Color(155, 117, 1));
        jTextFieldCompanyMobile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jTextFieldCompanyMobile.setDoubleBuffered(true);
        jTextFieldCompanyMobile.setPreferredSize(new java.awt.Dimension(161, 25));

        jLabelAddress.setBackground(new java.awt.Color(221, 217, 214));
        jLabelAddress.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelAddress.setForeground(new java.awt.Color(83, 66, 54));
        jLabelAddress.setText("Address:");

        jTextFieldAddress.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextFieldAddress.setForeground(new java.awt.Color(155, 117, 1));
        jTextFieldAddress.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jTextFieldAddress.setDoubleBuffered(true);
        jTextFieldAddress.setPreferredSize(new java.awt.Dimension(352, 30));

        jButtonInsert1.setBackground(new java.awt.Color(155, 117, 1));
        jButtonInsert1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonInsert1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInsert1.setText("Insert");
        jButtonInsert1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jButtonInsert1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonInsert1.setFocusable(false);
        jButtonInsert1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonInsert1.setPreferredSize(new java.awt.Dimension(73, 30));
        jButtonInsert1.setSelected(true);
        jButtonInsert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsert1ActionPerformed(evt);
            }
        });

        jButtonUpdate1.setBackground(new java.awt.Color(155, 117, 1));
        jButtonUpdate1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonUpdate1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate1.setText("Update");
        jButtonUpdate1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jButtonUpdate1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUpdate1.setFocusable(false);
        jButtonUpdate1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonUpdate1.setPreferredSize(new java.awt.Dimension(73, 30));
        jButtonUpdate1.setSelected(true);
        jButtonUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdate1ActionPerformed(evt);
            }
        });

        jButtonDelete1.setBackground(new java.awt.Color(155, 117, 1));
        jButtonDelete1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonDelete1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete1.setText("Delete");
        jButtonDelete1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jButtonDelete1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDelete1.setFocusable(false);
        jButtonDelete1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDelete1.setPreferredSize(new java.awt.Dimension(73, 30));
        jButtonDelete1.setSelected(true);
        jButtonDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelete1ActionPerformed(evt);
            }
        });

        jScrollPaneTableCompany.setBackground(new java.awt.Color(83, 66, 54));
        jScrollPaneTableCompany.setAutoscrolls(true);
        jScrollPaneTableCompany.setPreferredSize(new java.awt.Dimension(269, 189));

        jTableCompany.setAutoCreateRowSorter(true);
        jTableCompany.setBackground(new java.awt.Color(199, 189, 177));
        jTableCompany.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableCompany.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTableCompany.setForeground(new java.awt.Color(83, 66, 54));
        jTableCompany.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Mobile", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCompany.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableCompany.setGridColor(new java.awt.Color(255, 255, 255));
        jTableCompany.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTableCompany.setSelectionForeground(new java.awt.Color(155, 117, 1));
        jTableCompany.getTableHeader().setReorderingAllowed(false);
        jTableCompany.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableCompanyMouseReleased(evt);
            }
        });
        jScrollPaneTableCompany.setViewportView(jTableCompany);

        jTextFieldSearchCompany.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextFieldSearchCompany.setForeground(new java.awt.Color(83, 66, 54));
        jTextFieldSearchCompany.setText(" Search Company Name");
        jTextFieldSearchCompany.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(155, 117, 1)));
        jTextFieldSearchCompany.setDisabledTextColor(new java.awt.Color(221, 217, 214));
        jTextFieldSearchCompany.setPreferredSize(new java.awt.Dimension(129, 25));
        jTextFieldSearchCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchCompanyActionPerformed(evt);
            }
        });

        jLabelSearch1.setBackground(new java.awt.Color(83, 66, 54));
        jLabelSearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.png"))); // NOI18N

        jButtonClearCompanySearch.setBackground(new java.awt.Color(155, 117, 1));
        jButtonClearCompanySearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/clear.png"))); // NOI18N
        jButtonClearCompanySearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        jButtonClearCompanySearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClearCompanySearch.setPreferredSize(new java.awt.Dimension(25, 25));
        jButtonClearCompanySearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearCompanySearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCompanyLayout = new javax.swing.GroupLayout(jPanelCompany);
        jPanelCompany.setLayout(jPanelCompanyLayout);
        jPanelCompanyLayout.setHorizontalGroup(
            jPanelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCompanyLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCompanyLayout.createSequentialGroup()
                        .addComponent(jButtonInsert1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24)
                        .addComponent(jButtonUpdate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25)
                        .addComponent(jButtonDelete1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCompanyLayout.createSequentialGroup()
                        .addComponent(jLabelAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(114, 114, 114))
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelCompanyLayout.createSequentialGroup()
                        .addGroup(jPanelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCompanyLayout.createSequentialGroup()
                                .addComponent(jLabelCompanyName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(67, 67, 67))
                            .addGroup(jPanelCompanyLayout.createSequentialGroup()
                                .addGroup(jPanelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCompanies)
                                    .addComponent(jTextFieldCompanyName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(24, 24, 24)))
                        .addGroup(jPanelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCompanyMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCompanyMobile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPaneTableCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelCompanyLayout.createSequentialGroup()
                        .addComponent(jLabelSearch1)
                        .addGap(0, 0, 0)
                        .addComponent(jTextFieldSearchCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClearCompanySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)))
                .addGap(22, 22, 22))
        );
        jPanelCompanyLayout.setVerticalGroup(
            jPanelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCompanyLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelCompanies)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCompanyLayout.createSequentialGroup()
                        .addGroup(jPanelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCompanyName)
                            .addComponent(jLabelCompanyMobile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCompanyMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonInsert1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSearchCompany, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSearch1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonClearCompanySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTableCompany, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelScreenLayout = new javax.swing.GroupLayout(jPanelScreen);
        jPanelScreen.setLayout(jPanelScreenLayout);
        jPanelScreenLayout.setHorizontalGroup(
            jPanelScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelScreenLayout.createSequentialGroup()
                .addComponent(jPanelSuplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanelCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelScreenLayout.setVerticalGroup(
            jPanelScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSuplier, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
            .addComponent(jPanelCompany, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelScreen, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(816, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInsert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsert1ActionPerformed
        //get data
        String name = jTextFieldCompanyName.getText();
        String mobile = jTextFieldCompanyMobile.getText();
        String address = jTextFieldAddress.getText();

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the  Name", "Warning", JOptionPane.ERROR_MESSAGE);
            jTextFieldCompanyName.grabFocus();

        } else if (mobile.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the Contact Number", "Warning", JOptionPane.ERROR_MESSAGE);
            jTextFieldCompanyMobile.grabFocus();

        } else if (!mobile.matches("^\\+?[1-9]\\d{1,14}$")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid Mobile Number", "Warning", JOptionPane.ERROR_MESSAGE);
            jTextFieldUserMobile1.requestFocus();

        } else {

            try {
                // Insert 
                MYSQL.execute("INSERT INTO `supplier` (, `name`, `mobile`, `address`) "
                        + "VALUES ('" + name + "', '" + mobile + "','" + address + "')");

                // Update table & clear form
                loadCompanies();
                resetcompany();

                //  Message
                JOptionPane.showMessageDialog(this, "New Account Created", "Successful", JOptionPane.PLAIN_MESSAGE);

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButtonInsert1ActionPerformed

    private void jButtonUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUpdate1ActionPerformed

    private void jButtonDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelete1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDelete1ActionPerformed

    private void jButtonDelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelete2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDelete2ActionPerformed

    private void jButtonInsert2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsert2ActionPerformed
        //get data
        String id = jTextFieldUserId.getText();
        String name = jTextFieldUserName.getText();
        String company = (String) jComboBox1.getSelectedItem();
        String mobile = jTextFieldUserMobile1.getText();

        String comp = String.valueOf(jComboBox1.getSelectedItem());
        // Retrieve the role ID from the role map
        company compid = companyMap.get(company);
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the  Name", "Warning", JOptionPane.ERROR_MESSAGE);
            jTextFieldUserName.grabFocus();

        } else if (company.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the company", "Warning", JOptionPane.ERROR_MESSAGE);
            jComboBox1.grabFocus();

        } else if (mobile.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the Contact Number", "Warning", JOptionPane.ERROR_MESSAGE);
            jTextFieldUserMobile1.grabFocus();

        } else if (!mobile.matches("^\\+?[1-9]\\d{1,14}$")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid Mobile Number", "Warning", JOptionPane.ERROR_MESSAGE);
            jTextFieldUserMobile1.requestFocus();

        } else {
            int compint = compid.getCompany_id();
            try {
                // Insert 
                MYSQL.execute("INSERT INTO `supplier` ( `sname`, `mobile`, `company_id`) "
                        + "VALUES ('" + name + "', '" + mobile + "', '" + mobile + "','" + compint + "')");

                // Update table & clear form
                loadSuppliers();
                resetSupplier();

                //  Message
                JOptionPane.showMessageDialog(this, "New Account Created", "Successful", JOptionPane.PLAIN_MESSAGE);

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButtonInsert2ActionPerformed

    private void jButtonUpdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdate2ActionPerformed
        int selectedRow = jTableSupliers.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
            jTableSupliers.grabFocus();
        } else {
            // Assuming that the ID column is at index 0 of the table model
            String name = jTextFieldUserName.getText().trim();
            String company = (String) jComboBox1.getSelectedItem();
            String mobile = jTextFieldUserMobile1.getText().trim();
            String address = jTextFieldAddress.getText().trim();  // Assuming you have an address field

            if (name.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter the Company Name", "Warning", JOptionPane.ERROR_MESSAGE);
                jTextFieldUserName.grabFocus();
            } else if ("Select".equals(company)) {
                JOptionPane.showMessageDialog(this, "Please select a Company", "Warning", JOptionPane.ERROR_MESSAGE);
                jComboBox1.grabFocus();
            } else if (mobile.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter the Contact Number", "Warning", JOptionPane.ERROR_MESSAGE);
                jTextFieldUserMobile1.grabFocus();
            } else if (!mobile.matches("^\\+?[1-9]\\d{1,14}$")) {
                JOptionPane.showMessageDialog(this, "Please enter a valid Mobile Number", "Warning", JOptionPane.ERROR_MESSAGE);
                jTextFieldUserMobile1.requestFocus();
            } else if (address.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter the Company Address", "Warning", JOptionPane.ERROR_MESSAGE);
                jTextFieldAddress.grabFocus();
            } else {

                try {
                    
                    int accountId = Integer.parseInt((String) jTableSupliers.getValueAt(selectedRow, 0));

                    // Execute the update query
                    MYSQL.execute("");

                    // Update the table and reset the form
                    loadCorparates();
                    resetForm();

                    // Show success message
                    JOptionPane.showMessageDialog(this, "Update successful.", "Success", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Update failed.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }

    }//GEN-LAST:event_jButtonUpdate2ActionPerformed

    private void jTextFieldSearchSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchSuplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchSuplierActionPerformed

    private void jButtonClearNicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearNicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClearNicActionPerformed

    private void jTextFieldSearchCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchCompanyActionPerformed

    private void jButtonClearCompanySearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearCompanySearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClearCompanySearchActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        UserManagement userManagement = new UserManagement();
        userManagement.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void jTextFieldUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserIdActionPerformed

    private void jTableSupliersMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSupliersMouseReleased
        int[] selectedRows = jTableSupliers.getSelectedRows();

        if (selectedRows.length == 1) {
            int selectedRow = selectedRows[0];
            String id = String.valueOf(jTableSupliers.getValueAt(selectedRow, 0));
            String name = String.valueOf(jTableSupliers.getValueAt(selectedRow, 1));
            String company = String.valueOf(jTableSupliers.getValueAt(selectedRow, 2));
            String mobile = String.valueOf(jTableSupliers.getValueAt(selectedRow, 3));

            // Set the values to the respective UI components
            jTextFieldUserId.setText(id);
            jTextFieldUserName.setText(name);
            jComboBox1.setSelectedItem(company);
            jTextFieldUserMobile1.setText(mobile);

        } else {
            // Handle the case when no row or more than one row is selected
            JOptionPane.showMessageDialog(this, "Please select exactly one row", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jTableSupliersMouseReleased

    private void jTableCompanyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCompanyMouseReleased
        int[] selectedRows = jTableCompany.getSelectedRows();

        if (selectedRows.length == 1) {
            for (int selectedRow : selectedRows) {
                String name = String.valueOf(jTableCompany.getValueAt(selectedRow, 1));
                String mobile = String.valueOf(jTableCompany.getValueAt(selectedRow, 3));
                String address = String.valueOf(jTableCompany.getValueAt(selectedRow, 3));

                // Populate form fields
                jTextFieldCompanyName.setText(name);
                jTextFieldCompanyMobile.setText(mobile);
                jTextFieldAddress.setText(address);

            }
        }
    }//GEN-LAST:event_jTableCompanyMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supliers_companies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supliers_companies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supliers_companies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supliers_companies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supliers_companies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClearCompanySearch;
    private javax.swing.JButton jButtonClearNic;
    private javax.swing.JButton jButtonDelete1;
    private javax.swing.JButton jButtonDelete2;
    private javax.swing.JButton jButtonInsert1;
    private javax.swing.JButton jButtonInsert2;
    private javax.swing.JButton jButtonUpdate1;
    private javax.swing.JButton jButtonUpdate2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelCompanies;
    private javax.swing.JLabel jLabelCompanyMobile;
    private javax.swing.JLabel jLabelCompanyName;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelSearch1;
    private javax.swing.JLabel jLabelSupliers1;
    private javax.swing.JLabel jLabelUserCompany;
    private javax.swing.JLabel jLabelUserId;
    private javax.swing.JLabel jLabelUserMobile;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanelCompany;
    private javax.swing.JPanel jPanelScreen;
    private javax.swing.JPanel jPanelSuplier;
    private javax.swing.JScrollPane jScrollPaneTableCompany;
    private javax.swing.JScrollPane jScrollPaneTableSupliers1;
    private javax.swing.JTable jTableCompany;
    private javax.swing.JTable jTableSupliers;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldCompanyMobile;
    private javax.swing.JTextField jTextFieldCompanyName;
    private javax.swing.JTextField jTextFieldSearchCompany;
    private javax.swing.JTextField jTextFieldSearchSuplier;
    private javax.swing.JTextField jTextFieldUserId;
    private javax.swing.JTextField jTextFieldUserMobile1;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
