/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import GUI.UserManagement;
import java.sql.ResultSet;
import model.MYSQL;

/**
 *
 * @author DELL
 */
public class SystemConfiguration extends javax.swing.JFrame {

    /**
     * Creates new form systemConfig
     */
    public SystemConfiguration() {
        initComponents();
        Details();
    }

    private void Details() {
        try {
            // Fetch address
            ResultSet addressResultSet = MYSQL.execute("SELECT `Address` FROM hotel");
            if (addressResultSet.next()) {
                jTextFieldAddress.setText(addressResultSet.getString("Address"));
            }

            // Fetch mobile
            ResultSet mobileResultSet = MYSQL.execute("SELECT `Mobile` FROM hotel");
            if (mobileResultSet.next()) {
                jTextFieldMobile.setText(mobileResultSet.getString("Mobile"));
            }

            // Fetch email
            ResultSet emailResultSet = MYSQL.execute("SELECT `Email` FROM hotel");
            if (emailResultSet.next()) {
                jTextFieldMail.setText(emailResultSet.getString("Email"));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelDashboard = new javax.swing.JLabel();
        jLabelUserManagement = new javax.swing.JLabel();
        jLabelLogsAudit = new javax.swing.JLabel();
        jLabelLogOut = new javax.swing.JLabel();
        jPanelCurrent = new javax.swing.JPanel();
        jLabelSystemconfiguration = new javax.swing.JLabel();
        jPaneluser = new javax.swing.JPanel();
        jLabelUseImg = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelUserId = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jPanelScreen = new javax.swing.JPanel();
        jPanelGeneralSettings = new javax.swing.JPanel();
        jLabelUserDetails1 = new javax.swing.JLabel();
        jLabelHotelName = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jLabelMobile = new javax.swing.JLabel();
        jLabelMail = new javax.swing.JLabel();
        jTextFieldHotelName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jTextFieldMobile = new javax.swing.JTextField();
        jTextFieldMail = new javax.swing.JTextField();
        jButtonEdit = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jPanelTotal = new javax.swing.JPanel();
        jLabelStaff = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabelAvailable = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jButtonChangeStatus = new javax.swing.JButton();
        jRadioButtonon = new javax.swing.JRadioButton();
        jRadioButtonOff = new javax.swing.JRadioButton();
        jTextFieldAvailable = new javax.swing.JTextField();
        jPanelRoomConfig = new javax.swing.JPanel();
        jLabelUserDetails2 = new javax.swing.JLabel();
        jPanelRoomCount = new javax.swing.JPanel();
        jLabelAvailableRooms = new javax.swing.JLabel();
        jLabelRoomAvailable = new javax.swing.JLabel();
        jLabelRoomTotal = new javax.swing.JLabel();
        jLabelTotalRooms = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelRoomNo = new javax.swing.JLabel();
        jButtonSearch = new javax.swing.JButton();
        jSpinnerRoomNo = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jRadioButtonAvailable = new javax.swing.JRadioButton();
        jLabelStatusRoom = new javax.swing.JLabel();
        jRadioButtonBooked = new javax.swing.JRadioButton();
        jLabelRoomType = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxRoomeType = new javax.swing.JComboBox<>();
        jLabelPrice = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField();
        jLabelDescription = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPaneDescription = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonManageRooms = new javax.swing.JButton();
        jButtonSaveRoom = new javax.swing.JButton();
        jButtonEditRoom = new javax.swing.JButton();
        jButtonChangeRoomStatus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMenu.setBackground(new java.awt.Color(83, 66, 54));
        jPanelMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelMenu.setPreferredSize(new java.awt.Dimension(200, 500));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N

        jLabelDashboard.setBackground(new java.awt.Color(83, 66, 54));
        jLabelDashboard.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabelDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDashboard.setText("Dashboard");
        jLabelDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDashboardMouseClicked(evt);
            }
        });

        jLabelUserManagement.setBackground(new java.awt.Color(83, 66, 54));
        jLabelUserManagement.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabelUserManagement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserManagement.setText("User Managent");
        jLabelUserManagement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelUserManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUserManagementMouseClicked(evt);
            }
        });

        jLabelLogsAudit.setBackground(new java.awt.Color(83, 66, 54));
        jLabelLogsAudit.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabelLogsAudit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogsAudit.setText("Logs/Audit Trails");
        jLabelLogsAudit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLogsAudit.setPreferredSize(null);
        jLabelLogsAudit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogsAuditMouseClicked(evt);
            }
        });

        jLabelLogOut.setBackground(new java.awt.Color(83, 66, 54));
        jLabelLogOut.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabelLogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogOut.setText("Log Out");
        jLabelLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLogOut.setPreferredSize(null);

        jPanelCurrent.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCurrent.setPreferredSize(new java.awt.Dimension(199, 32));

        jLabelSystemconfiguration.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSystemconfiguration.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabelSystemconfiguration.setForeground(new java.awt.Color(83, 66, 54));
        jLabelSystemconfiguration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSystemconfiguration.setText("System Configuration");
        jLabelSystemconfiguration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSystemconfiguration.setPreferredSize(null);

        javax.swing.GroupLayout jPanelCurrentLayout = new javax.swing.GroupLayout(jPanelCurrent);
        jPanelCurrent.setLayout(jPanelCurrentLayout);
        jPanelCurrentLayout.setHorizontalGroup(
            jPanelCurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSystemconfiguration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelCurrentLayout.setVerticalGroup(
            jPanelCurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSystemconfiguration, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jPaneluser.setBackground(new java.awt.Color(83, 66, 54));
        jPaneluser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPaneluser.setPreferredSize(new java.awt.Dimension(199, 72));

        jLabelUseImg.setBackground(new java.awt.Color(83, 66, 54));
        jLabelUseImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/user.png"))); // NOI18N

        jLabelId.setBackground(new java.awt.Color(83, 66, 54));
        jLabelId.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabelId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelId.setText("ID     : ");
        jLabelId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelUserName.setBackground(new java.awt.Color(83, 66, 54));
        jLabelUserName.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabelUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserName.setText("Shehara");
        jLabelUserName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelUserId.setBackground(new java.awt.Color(83, 66, 54));
        jLabelUserId.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabelUserId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserId.setText("RS0001");
        jLabelUserId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelName.setBackground(new java.awt.Color(83, 66, 54));
        jLabelName.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelName.setText("Name:");
        jLabelName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPaneluserLayout = new javax.swing.GroupLayout(jPaneluser);
        jPaneluser.setLayout(jPaneluserLayout);
        jPaneluserLayout.setHorizontalGroup(
            jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneluserLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabelUseImg)
                .addGap(10, 10, 10)
                .addGroup(jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneluserLayout.createSequentialGroup()
                        .addComponent(jLabelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUserId))
                    .addGroup(jPaneluserLayout.createSequentialGroup()
                        .addComponent(jLabelName)
                        .addGap(3, 3, 3)
                        .addComponent(jLabelUserName)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPaneluserLayout.setVerticalGroup(
            jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneluserLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUseImg)
                    .addGroup(jPaneluserLayout.createSequentialGroup()
                        .addGroup(jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUserId))
                        .addGap(4, 4, 4)
                        .addGroup(jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelName)
                            .addComponent(jLabelUserName)))))
        );

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPaneluser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelMenuLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabelLogo))
                            .addComponent(jLabelLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelCurrent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLogsAudit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelUserManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addComponent(jLabelLogo)
                .addGap(30, 30, 30)
                .addComponent(jLabelDashboard)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabelUserManagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanelCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabelLogsAudit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jLabelLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPaneluser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanelMenu, java.awt.BorderLayout.LINE_START);

        jPanelScreen.setBackground(new java.awt.Color(255, 255, 255));

        jPanelGeneralSettings.setBackground(new java.awt.Color(199, 189, 177));
        jPanelGeneralSettings.setPreferredSize(new java.awt.Dimension(289, 212));

        jLabelUserDetails1.setBackground(new java.awt.Color(199, 189, 177));
        jLabelUserDetails1.setFont(new java.awt.Font("SansSerif", 3, 25)); // NOI18N
        jLabelUserDetails1.setForeground(new java.awt.Color(83, 66, 54));
        jLabelUserDetails1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserDetails1.setText("General Settings");
        jLabelUserDetails1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(83, 66, 54)));
        jLabelUserDetails1.setPreferredSize(new java.awt.Dimension(201, 25));

        jLabelHotelName.setBackground(new java.awt.Color(199, 189, 177));
        jLabelHotelName.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelHotelName.setForeground(new java.awt.Color(83, 66, 54));
        jLabelHotelName.setText("Hotel Mame");
        jLabelHotelName.setPreferredSize(new java.awt.Dimension(84, 25));

        jLabelAddress.setBackground(new java.awt.Color(199, 189, 177));
        jLabelAddress.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelAddress.setForeground(new java.awt.Color(83, 66, 54));
        jLabelAddress.setText("Address");
        jLabelAddress.setPreferredSize(new java.awt.Dimension(84, 25));

        jLabelMobile.setBackground(new java.awt.Color(199, 189, 177));
        jLabelMobile.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelMobile.setForeground(new java.awt.Color(83, 66, 54));
        jLabelMobile.setText("Mobile No.");
        jLabelMobile.setPreferredSize(new java.awt.Dimension(84, 25));

        jLabelMail.setBackground(new java.awt.Color(199, 189, 177));
        jLabelMail.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelMail.setForeground(new java.awt.Color(83, 66, 54));
        jLabelMail.setText("E-mail");
        jLabelMail.setPreferredSize(new java.awt.Dimension(84, 25));

        jTextFieldHotelName.setBackground(new java.awt.Color(199, 189, 177));
        jTextFieldHotelName.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextFieldHotelName.setForeground(new java.awt.Color(155, 117, 1));
        jTextFieldHotelName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldHotelName.setText(" Pearl Palace");
        jTextFieldHotelName.setBorder(null);
        jTextFieldHotelName.setCaretColor(new java.awt.Color(199, 189, 177));
        jTextFieldHotelName.setDisabledTextColor(new java.awt.Color(155, 117, 1));
        jTextFieldHotelName.setPreferredSize(new java.awt.Dimension(142, 25));
        jTextFieldHotelName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHotelNameActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(199, 189, 177));
        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(83, 66, 54));
        jLabel5.setText(":");
        jLabel5.setPreferredSize(new java.awt.Dimension(84, 25));

        jLabel6.setBackground(new java.awt.Color(199, 189, 177));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(83, 66, 54));
        jLabel6.setText(":");
        jLabel6.setPreferredSize(new java.awt.Dimension(84, 25));

        jLabel7.setBackground(new java.awt.Color(199, 189, 177));
        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(83, 66, 54));
        jLabel7.setText(":");
        jLabel7.setPreferredSize(new java.awt.Dimension(84, 25));

        jLabel8.setBackground(new java.awt.Color(199, 189, 177));
        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(83, 66, 54));
        jLabel8.setText(":");
        jLabel8.setPreferredSize(new java.awt.Dimension(84, 25));

        jTextFieldAddress.setEditable(false);
        jTextFieldAddress.setBackground(new java.awt.Color(221, 217, 214));
        jTextFieldAddress.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextFieldAddress.setForeground(new java.awt.Color(155, 117, 1));
        jTextFieldAddress.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177)));
        jTextFieldAddress.setDisabledTextColor(new java.awt.Color(155, 117, 1));
        jTextFieldAddress.setPreferredSize(new java.awt.Dimension(142, 25));
        jTextFieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressActionPerformed(evt);
            }
        });

        jTextFieldMobile.setEditable(false);
        jTextFieldMobile.setBackground(new java.awt.Color(221, 217, 214));
        jTextFieldMobile.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextFieldMobile.setForeground(new java.awt.Color(155, 117, 1));
        jTextFieldMobile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177)));
        jTextFieldMobile.setCaretColor(new java.awt.Color(221, 217, 214));
        jTextFieldMobile.setDisabledTextColor(new java.awt.Color(155, 117, 1));
        jTextFieldMobile.setPreferredSize(new java.awt.Dimension(142, 25));
        jTextFieldMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMobileActionPerformed(evt);
            }
        });

        jTextFieldMail.setEditable(false);
        jTextFieldMail.setBackground(new java.awt.Color(221, 217, 214));
        jTextFieldMail.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextFieldMail.setForeground(new java.awt.Color(155, 117, 1));
        jTextFieldMail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177)));
        jTextFieldMail.setCaretColor(new java.awt.Color(221, 217, 214));
        jTextFieldMail.setDisabledTextColor(new java.awt.Color(155, 117, 1));
        jTextFieldMail.setPreferredSize(new java.awt.Dimension(142, 25));
        jTextFieldMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMailActionPerformed(evt);
            }
        });

        jButtonEdit.setBackground(new java.awt.Color(83, 66, 54));
        jButtonEdit.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonEdit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEdit.setText("Edit");
        jButtonEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177)));
        jButtonEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEdit.setFocusable(false);
        jButtonEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEdit.setPreferredSize(new java.awt.Dimension(83, 25));
        jButtonEdit.setSelected(true);
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonSave.setBackground(new java.awt.Color(83, 66, 54));
        jButtonSave.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonSave.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSave.setText("Save");
        jButtonSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177)));
        jButtonSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSave.setFocusable(false);
        jButtonSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSave.setPreferredSize(new java.awt.Dimension(83, 25));
        jButtonSave.setSelected(true);
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGeneralSettingsLayout = new javax.swing.GroupLayout(jPanelGeneralSettings);
        jPanelGeneralSettings.setLayout(jPanelGeneralSettingsLayout);
        jPanelGeneralSettingsLayout.setHorizontalGroup(
            jPanelGeneralSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralSettingsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelGeneralSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelMail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMobile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelHotelName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGeneralSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanelGeneralSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldMail, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(jTextFieldMobile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelGeneralSettingsLayout.createSequentialGroup()
                        .addComponent(jTextFieldHotelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(jPanelGeneralSettingsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelUserDetails1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelGeneralSettingsLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButtonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addComponent(jButtonSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(55, 55, 55))
        );
        jPanelGeneralSettingsLayout.setVerticalGroup(
            jPanelGeneralSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralSettingsLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelUserDetails1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGeneralSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHotelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHotelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGeneralSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGeneralSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGeneralSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanelGeneralSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanelTotal.setBackground(new java.awt.Color(199, 189, 177));
        jPanelTotal.setPreferredSize(new java.awt.Dimension(246, 212));

        jLabelStaff.setBackground(new java.awt.Color(199, 189, 177));
        jLabelStaff.setFont(new java.awt.Font("SansSerif", 3, 25)); // NOI18N
        jLabelStaff.setForeground(new java.awt.Color(83, 66, 54));
        jLabelStaff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStaff.setText("Availability Staff");
        jLabelStaff.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(83, 66, 54)));
        jLabelStaff.setPreferredSize(new java.awt.Dimension(192, 25));

        jLabelTotal.setBackground(new java.awt.Color(199, 189, 177));
        jLabelTotal.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelTotal.setForeground(new java.awt.Color(83, 66, 54));
        jLabelTotal.setText("Total Staff");
        jLabelTotal.setPreferredSize(new java.awt.Dimension(84, 25));

        jLabelAvailable.setBackground(new java.awt.Color(199, 189, 177));
        jLabelAvailable.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelAvailable.setForeground(new java.awt.Color(83, 66, 54));
        jLabelAvailable.setText("Available");
        jLabelAvailable.setPreferredSize(new java.awt.Dimension(84, 25));

        jLabelUser.setBackground(new java.awt.Color(199, 189, 177));
        jLabelUser.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelUser.setForeground(new java.awt.Color(83, 66, 54));
        jLabelUser.setText("User ID");
        jLabelUser.setPreferredSize(new java.awt.Dimension(84, 25));

        jLabelStatus.setBackground(new java.awt.Color(199, 189, 177));
        jLabelStatus.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(83, 66, 54));
        jLabelStatus.setText("Status");
        jLabelStatus.setPreferredSize(new java.awt.Dimension(84, 25));

        jTextFieldTotal.setBackground(new java.awt.Color(199, 189, 177));
        jTextFieldTotal.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextFieldTotal.setForeground(new java.awt.Color(155, 117, 1));
        jTextFieldTotal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldTotal.setText(" 178");
        jTextFieldTotal.setBorder(null);
        jTextFieldTotal.setCaretColor(new java.awt.Color(199, 189, 177));
        jTextFieldTotal.setDisabledTextColor(new java.awt.Color(155, 117, 1));
        jTextFieldTotal.setDoubleBuffered(true);
        jTextFieldTotal.setPreferredSize(new java.awt.Dimension(115, 25));
        jTextFieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(199, 189, 177));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(83, 66, 54));
        jLabel1.setText(":");
        jLabel1.setPreferredSize(new java.awt.Dimension(84, 25));

        jLabel2.setBackground(new java.awt.Color(199, 189, 177));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(83, 66, 54));
        jLabel2.setText(":");
        jLabel2.setPreferredSize(new java.awt.Dimension(84, 25));

        jLabel3.setBackground(new java.awt.Color(199, 189, 177));
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(83, 66, 54));
        jLabel3.setText(":");
        jLabel3.setPreferredSize(new java.awt.Dimension(84, 25));

        jLabel4.setBackground(new java.awt.Color(199, 189, 177));
        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(83, 66, 54));
        jLabel4.setText(":");
        jLabel4.setPreferredSize(new java.awt.Dimension(84, 25));

        jTextFieldUser.setBackground(new java.awt.Color(221, 217, 214));
        jTextFieldUser.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextFieldUser.setForeground(new java.awt.Color(155, 117, 1));
        jTextFieldUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177)));
        jTextFieldUser.setCaretColor(new java.awt.Color(221, 217, 214));
        jTextFieldUser.setDoubleBuffered(true);
        jTextFieldUser.setPreferredSize(new java.awt.Dimension(115, 25));
        jTextFieldUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserActionPerformed(evt);
            }
        });

        jButtonChangeStatus.setBackground(new java.awt.Color(83, 66, 54));
        jButtonChangeStatus.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonChangeStatus.setForeground(new java.awt.Color(255, 255, 255));
        jButtonChangeStatus.setText("Change Status");
        jButtonChangeStatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177)));
        jButtonChangeStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonChangeStatus.setFocusable(false);
        jButtonChangeStatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonChangeStatus.setPreferredSize(new java.awt.Dimension(130, 25));
        jButtonChangeStatus.setSelected(true);
        jButtonChangeStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeStatusActionPerformed(evt);
            }
        });

        jRadioButtonon.setBackground(new java.awt.Color(199, 189, 177));
        jRadioButtonon.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jRadioButtonon.setForeground(new java.awt.Color(155, 117, 1));
        jRadioButtonon.setText("On");
        jRadioButtonon.setPreferredSize(new java.awt.Dimension(50, 25));

        jRadioButtonOff.setBackground(new java.awt.Color(199, 189, 177));
        jRadioButtonOff.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jRadioButtonOff.setForeground(new java.awt.Color(155, 117, 1));
        jRadioButtonOff.setText("Off");
        jRadioButtonOff.setPreferredSize(new java.awt.Dimension(50, 25));
        jRadioButtonOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOffActionPerformed(evt);
            }
        });

        jTextFieldAvailable.setBackground(new java.awt.Color(199, 189, 177));
        jTextFieldAvailable.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextFieldAvailable.setForeground(new java.awt.Color(155, 117, 1));
        jTextFieldAvailable.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldAvailable.setText(" 98");
        jTextFieldAvailable.setBorder(null);
        jTextFieldAvailable.setCaretColor(new java.awt.Color(199, 189, 177));
        jTextFieldAvailable.setDisabledTextColor(new java.awt.Color(155, 117, 1));
        jTextFieldAvailable.setDoubleBuffered(true);
        jTextFieldAvailable.setPreferredSize(new java.awt.Dimension(115, 25));
        jTextFieldAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAvailableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTotalLayout = new javax.swing.GroupLayout(jPanelTotal);
        jPanelTotal.setLayout(jPanelTotalLayout);
        jPanelTotalLayout.setHorizontalGroup(
            jPanelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTotalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelAvailable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelTotalLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jRadioButtonon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonOff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldAvailable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTotalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelTotalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonChangeStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTotalLayout.setVerticalGroup(
            jPanelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTotalLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonChangeStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanelRoomConfig.setBackground(new java.awt.Color(199, 189, 177));
        jPanelRoomConfig.setPreferredSize(new java.awt.Dimension(568, 237));

        jLabelUserDetails2.setBackground(new java.awt.Color(199, 189, 177));
        jLabelUserDetails2.setFont(new java.awt.Font("SansSerif", 3, 25)); // NOI18N
        jLabelUserDetails2.setForeground(new java.awt.Color(83, 66, 54));
        jLabelUserDetails2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserDetails2.setText("Room Configuration");
        jLabelUserDetails2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(83, 66, 54)));
        jLabelUserDetails2.setPreferredSize(new java.awt.Dimension(251, 25));

        jPanelRoomCount.setBackground(new java.awt.Color(199, 189, 177));
        jPanelRoomCount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRoomCount.setPreferredSize(new java.awt.Dimension(319, 26));

        jLabelAvailableRooms.setBackground(new java.awt.Color(199, 189, 177));
        jLabelAvailableRooms.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelAvailableRooms.setForeground(new java.awt.Color(83, 66, 54));
        jLabelAvailableRooms.setText("Available :");
        jLabelAvailableRooms.setPreferredSize(new java.awt.Dimension(96, 25));

        jLabelRoomAvailable.setBackground(new java.awt.Color(199, 189, 177));
        jLabelRoomAvailable.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelRoomAvailable.setForeground(new java.awt.Color(155, 117, 1));
        jLabelRoomAvailable.setText("100");
        jLabelRoomAvailable.setPreferredSize(new java.awt.Dimension(25, 20));

        jLabelRoomTotal.setBackground(new java.awt.Color(199, 189, 177));
        jLabelRoomTotal.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelRoomTotal.setForeground(new java.awt.Color(155, 117, 1));
        jLabelRoomTotal.setText("100");
        jLabelRoomTotal.setPreferredSize(new java.awt.Dimension(25, 20));

        jLabelTotalRooms.setBackground(new java.awt.Color(199, 189, 177));
        jLabelTotalRooms.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelTotalRooms.setForeground(new java.awt.Color(83, 66, 54));
        jLabelTotalRooms.setText("Total Rooms :");
        jLabelTotalRooms.setPreferredSize(new java.awt.Dimension(96, 25));

        javax.swing.GroupLayout jPanelRoomCountLayout = new javax.swing.GroupLayout(jPanelRoomCount);
        jPanelRoomCount.setLayout(jPanelRoomCountLayout);
        jPanelRoomCountLayout.setHorizontalGroup(
            jPanelRoomCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRoomCountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTotalRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRoomTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabelAvailableRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRoomAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanelRoomCountLayout.setVerticalGroup(
            jPanelRoomCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRoomCountLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanelRoomCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAvailableRooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRoomAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRoomTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTotalRooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel11.setBackground(new java.awt.Color(199, 189, 177));
        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(83, 66, 54));
        jLabel11.setText(":");
        jLabel11.setPreferredSize(new java.awt.Dimension(84, 25));

        jLabelRoomNo.setBackground(new java.awt.Color(199, 189, 177));
        jLabelRoomNo.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelRoomNo.setForeground(new java.awt.Color(83, 66, 54));
        jLabelRoomNo.setText("Room No.");
        jLabelRoomNo.setPreferredSize(new java.awt.Dimension(84, 30));

        jButtonSearch.setBackground(new java.awt.Color(83, 66, 54));
        jButtonSearch.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonSearch.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search_white.png"))); // NOI18N
        jButtonSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177)));
        jButtonSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSearch.setFocusable(false);
        jButtonSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSearch.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonSearch.setSelected(true);
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jSpinnerRoomNo.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jSpinnerRoomNo.setModel(new javax.swing.SpinnerNumberModel(100, 0, 100, 1));
        jSpinnerRoomNo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177)));
        jSpinnerRoomNo.setPreferredSize(new java.awt.Dimension(50, 30));

        jLabel12.setBackground(new java.awt.Color(199, 189, 177));
        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(83, 66, 54));
        jLabel12.setText(":");
        jLabel12.setPreferredSize(new java.awt.Dimension(84, 25));

        jRadioButtonAvailable.setBackground(new java.awt.Color(199, 189, 177));
        jRadioButtonAvailable.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jRadioButtonAvailable.setForeground(new java.awt.Color(155, 117, 1));
        jRadioButtonAvailable.setText("Available");
        jRadioButtonAvailable.setPreferredSize(new java.awt.Dimension(93, 25));
        jRadioButtonAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAvailableActionPerformed(evt);
            }
        });

        jLabelStatusRoom.setBackground(new java.awt.Color(199, 189, 177));
        jLabelStatusRoom.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelStatusRoom.setForeground(new java.awt.Color(83, 66, 54));
        jLabelStatusRoom.setText("Status");
        jLabelStatusRoom.setPreferredSize(new java.awt.Dimension(84, 25));

        jRadioButtonBooked.setBackground(new java.awt.Color(199, 189, 177));
        jRadioButtonBooked.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jRadioButtonBooked.setForeground(new java.awt.Color(155, 117, 1));
        jRadioButtonBooked.setText("Booked");
        jRadioButtonBooked.setPreferredSize(new java.awt.Dimension(93, 25));
        jRadioButtonBooked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBookedActionPerformed(evt);
            }
        });

        jLabelRoomType.setBackground(new java.awt.Color(199, 189, 177));
        jLabelRoomType.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelRoomType.setForeground(new java.awt.Color(83, 66, 54));
        jLabelRoomType.setText("Room Type");
        jLabelRoomType.setPreferredSize(new java.awt.Dimension(84, 30));

        jLabel13.setBackground(new java.awt.Color(199, 189, 177));
        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(83, 66, 54));
        jLabel13.setText(":");
        jLabel13.setPreferredSize(new java.awt.Dimension(11, 30));

        jComboBoxRoomeType.setBackground(new java.awt.Color(221, 217, 214));
        jComboBoxRoomeType.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jComboBoxRoomeType.setForeground(new java.awt.Color(155, 117, 1));
        jComboBoxRoomeType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxRoomeType.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177)));
        jComboBoxRoomeType.setPreferredSize(new java.awt.Dimension(200, 30));
        jComboBoxRoomeType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRoomeTypeActionPerformed(evt);
            }
        });

        jLabelPrice.setBackground(new java.awt.Color(199, 189, 177));
        jLabelPrice.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelPrice.setForeground(new java.awt.Color(83, 66, 54));
        jLabelPrice.setText("Price");
        jLabelPrice.setPreferredSize(new java.awt.Dimension(84, 25));

        jLabel14.setBackground(new java.awt.Color(199, 189, 177));
        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(83, 66, 54));
        jLabel14.setText(":");
        jLabel14.setPreferredSize(new java.awt.Dimension(11, 25));

        jTextFieldPrice.setBackground(new java.awt.Color(221, 217, 214));
        jTextFieldPrice.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextFieldPrice.setForeground(new java.awt.Color(155, 117, 1));
        jTextFieldPrice.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177)));
        jTextFieldPrice.setCaretColor(new java.awt.Color(221, 217, 214));
        jTextFieldPrice.setDisabledTextColor(new java.awt.Color(155, 117, 1));
        jTextFieldPrice.setPreferredSize(new java.awt.Dimension(200, 25));
        jTextFieldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPriceActionPerformed(evt);
            }
        });

        jLabelDescription.setBackground(new java.awt.Color(199, 189, 177));
        jLabelDescription.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelDescription.setForeground(new java.awt.Color(83, 66, 54));
        jLabelDescription.setText("Description");
        jLabelDescription.setPreferredSize(new java.awt.Dimension(84, 25));

        jLabel15.setBackground(new java.awt.Color(199, 189, 177));
        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(83, 66, 54));
        jLabel15.setText(":");
        jLabel15.setPreferredSize(new java.awt.Dimension(11, 25));

        jScrollPaneDescription.setBackground(new java.awt.Color(221, 217, 214));
        jScrollPaneDescription.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jScrollPaneDescription.setToolTipText("");
        jScrollPaneDescription.setPreferredSize(new java.awt.Dimension(200, 35));
        jScrollPaneDescription.setRequestFocusEnabled(false);

        jTextAreaDescription.setBackground(new java.awt.Color(221, 217, 214));
        jTextAreaDescription.setColumns(1);
        jTextAreaDescription.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextAreaDescription.setForeground(new java.awt.Color(155, 117, 1));
        jTextAreaDescription.setLineWrap(true);
        jTextAreaDescription.setRows(3);
        jTextAreaDescription.setTabSize(15);
        jTextAreaDescription.setBorder(null);
        jTextAreaDescription.setDisabledTextColor(new java.awt.Color(155, 117, 1));
        jTextAreaDescription.setPreferredSize(new java.awt.Dimension(2016, 60));
        jScrollPaneDescription.setViewportView(jTextAreaDescription);

        jSeparator1.setBackground(new java.awt.Color(199, 189, 177));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(2, 154));

        jButtonManageRooms.setBackground(new java.awt.Color(83, 66, 54));
        jButtonManageRooms.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonManageRooms.setForeground(new java.awt.Color(255, 255, 255));
        jButtonManageRooms.setText("Manage Rooms");
        jButtonManageRooms.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177)));
        jButtonManageRooms.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonManageRooms.setFocusable(false);
        jButtonManageRooms.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonManageRooms.setPreferredSize(new java.awt.Dimension(83, 25));
        jButtonManageRooms.setSelected(true);
        jButtonManageRooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonManageRoomsMouseClicked(evt);
            }
        });
        jButtonManageRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageRoomsActionPerformed(evt);
            }
        });

        jButtonSaveRoom.setBackground(new java.awt.Color(83, 66, 54));
        jButtonSaveRoom.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonSaveRoom.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSaveRoom.setText("Save");
        jButtonSaveRoom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177)));
        jButtonSaveRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSaveRoom.setFocusable(false);
        jButtonSaveRoom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSaveRoom.setPreferredSize(new java.awt.Dimension(50, 25));
        jButtonSaveRoom.setSelected(true);
        jButtonSaveRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveRoomActionPerformed(evt);
            }
        });

        jButtonEditRoom.setBackground(new java.awt.Color(83, 66, 54));
        jButtonEditRoom.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonEditRoom.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditRoom.setText("Edit");
        jButtonEditRoom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177)));
        jButtonEditRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditRoom.setFocusable(false);
        jButtonEditRoom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEditRoom.setPreferredSize(new java.awt.Dimension(50, 25));
        jButtonEditRoom.setSelected(true);
        jButtonEditRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditRoomActionPerformed(evt);
            }
        });

        jButtonChangeRoomStatus.setBackground(new java.awt.Color(83, 66, 54));
        jButtonChangeRoomStatus.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonChangeRoomStatus.setForeground(new java.awt.Color(255, 255, 255));
        jButtonChangeRoomStatus.setText("Change Status");
        jButtonChangeRoomStatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177), new java.awt.Color(199, 189, 177)));
        jButtonChangeRoomStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonChangeRoomStatus.setFocusable(false);
        jButtonChangeRoomStatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonChangeRoomStatus.setPreferredSize(new java.awt.Dimension(130, 25));
        jButtonChangeRoomStatus.setSelected(true);
        jButtonChangeRoomStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeRoomStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRoomConfigLayout = new javax.swing.GroupLayout(jPanelRoomConfig);
        jPanelRoomConfig.setLayout(jPanelRoomConfigLayout);
        jPanelRoomConfigLayout.setHorizontalGroup(
            jPanelRoomConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRoomConfigLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelRoomConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRoomConfigLayout.createSequentialGroup()
                        .addGroup(jPanelRoomConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRoomNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelStatusRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRoomConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRoomConfigLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jSpinnerRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRoomConfigLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addGroup(jPanelRoomConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jRadioButtonBooked, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButtonAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jButtonChangeRoomStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRoomConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelRoomConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelRoomConfigLayout.createSequentialGroup()
                            .addComponent(jLabelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelRoomConfigLayout.createSequentialGroup()
                            .addComponent(jLabelRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelRoomConfigLayout.createSequentialGroup()
                            .addComponent(jLabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelRoomConfigLayout.createSequentialGroup()
                        .addComponent(jButtonEditRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSaveRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRoomConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxRoomeType, 0, 1, Short.MAX_VALUE)
                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jScrollPaneDescription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonManageRooms, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
            .addGroup(jPanelRoomConfigLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRoomConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelRoomCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRoomConfigLayout.createSequentialGroup()
                        .addComponent(jLabelUserDetails2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRoomConfigLayout.setVerticalGroup(
            jPanelRoomConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRoomConfigLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabelUserDetails2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanelRoomCount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRoomConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRoomConfigLayout.createSequentialGroup()
                        .addGroup(jPanelRoomConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelRoomConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxRoomeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelRoomConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelRoomConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addGroup(jPanelRoomConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelRoomConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonManageRooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelRoomConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonSaveRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonEditRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelRoomConfigLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanelRoomConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelRoomConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSpinnerRoomNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelRoomConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelStatusRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelRoomConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jRadioButtonAvailable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonBooked, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonChangeRoomStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelScreenLayout = new javax.swing.GroupLayout(jPanelScreen);
        jPanelScreen.setLayout(jPanelScreenLayout);
        jPanelScreenLayout.setHorizontalGroup(
            jPanelScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelScreenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelRoomConfig, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addGroup(jPanelScreenLayout.createSequentialGroup()
                        .addComponent(jPanelGeneralSettings, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                        .addGap(23, 23, 23)
                        .addComponent(jPanelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanelScreenLayout.setVerticalGroup(
            jPanelScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelScreenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelGeneralSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jPanelRoomConfig, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelScreen, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(816, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jTextFieldMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMailActionPerformed

    private void jTextFieldMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMobileActionPerformed

    private void jTextFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressActionPerformed

    }//GEN-LAST:event_jTextFieldAddressActionPerformed

    private void jTextFieldHotelNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHotelNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHotelNameActionPerformed

    private void jTextFieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalActionPerformed

    private void jTextFieldUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserActionPerformed

    private void jButtonChangeStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonChangeStatusActionPerformed

    private void jRadioButtonOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonOffActionPerformed

    private void jTextFieldAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAvailableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAvailableActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jRadioButtonAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAvailableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAvailableActionPerformed

    private void jRadioButtonBookedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBookedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonBookedActionPerformed

    private void jComboBoxRoomeTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRoomeTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRoomeTypeActionPerformed

    private void jTextFieldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPriceActionPerformed

    private void jButtonManageRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageRoomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonManageRoomsActionPerformed

    private void jButtonSaveRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSaveRoomActionPerformed

    private void jButtonEditRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditRoomActionPerformed

    private void jButtonChangeRoomStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeRoomStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonChangeRoomStatusActionPerformed

    private void jLabelUserManagementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUserManagementMouseClicked
        UserManagement userManagement = new UserManagement();// Get the new UserManagement
        userManagement.setVisible(true); // Show the new UserManagement
        this.setVisible(false); // Close the current window
    }//GEN-LAST:event_jLabelUserManagementMouseClicked

    private void jLabelDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDashboardMouseClicked
        AdminDashboard AdminDashboard = new AdminDashboard();// Get the new AdminDashboard
        AdminDashboard.setVisible(true); // Show the new UserManagement
        this.setVisible(false); // Close the current window
    }//GEN-LAST:event_jLabelDashboardMouseClicked

    private void jLabelLogsAuditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogsAuditMouseClicked
        Logs_Audit Logs_Audit = new Logs_Audit();// Get the new logs&audit
        Logs_Audit.setVisible(true); // Show the new logs&audit
        this.setVisible(false); // Close the current window
    }//GEN-LAST:event_jLabelLogsAuditMouseClicked

    private void jButtonManageRoomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonManageRoomsMouseClicked
        ManageRooms ManageRooms = new ManageRooms();// Instantiate the new UserDetails window
        ManageRooms.setVisible(true); // Show the UserDetails window
        this.setVisible(false);    // Hide the current window
    }//GEN-LAST:event_jButtonManageRoomsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemConfiguration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemConfiguration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemConfiguration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemConfiguration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemConfiguration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChangeRoomStatus;
    private javax.swing.JButton jButtonChangeStatus;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonEditRoom;
    private javax.swing.JButton jButtonManageRooms;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSaveRoom;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JComboBox<String> jComboBoxRoomeType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelAvailable;
    private javax.swing.JLabel jLabelAvailableRooms;
    private javax.swing.JLabel jLabelDashboard;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelHotelName;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelLogOut;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelLogsAudit;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelMobile;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelRoomAvailable;
    private javax.swing.JLabel jLabelRoomNo;
    private javax.swing.JLabel jLabelRoomTotal;
    private javax.swing.JLabel jLabelRoomType;
    private javax.swing.JLabel jLabelStaff;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelStatusRoom;
    private javax.swing.JLabel jLabelSystemconfiguration;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelTotalRooms;
    private javax.swing.JLabel jLabelUseImg;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JLabel jLabelUserDetails1;
    private javax.swing.JLabel jLabelUserDetails2;
    private javax.swing.JLabel jLabelUserId;
    private javax.swing.JLabel jLabelUserManagement;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanelCurrent;
    private javax.swing.JPanel jPanelGeneralSettings;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelRoomConfig;
    private javax.swing.JPanel jPanelRoomCount;
    private javax.swing.JPanel jPanelScreen;
    private javax.swing.JPanel jPanelTotal;
    private javax.swing.JPanel jPaneluser;
    private javax.swing.JRadioButton jRadioButtonAvailable;
    private javax.swing.JRadioButton jRadioButtonBooked;
    private javax.swing.JRadioButton jRadioButtonOff;
    private javax.swing.JRadioButton jRadioButtonon;
    private javax.swing.JScrollPane jScrollPaneDescription;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinnerRoomNo;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldAvailable;
    private javax.swing.JTextField jTextFieldHotelName;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldMobile;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldTotal;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
