/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import gui.AdminDashboard;
import gui.Logs_Audit;
import gui.SystemConfiguration;
import gui.UserDetails;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import model.MYSQL;

/**
 *
 * @author DELL
 */
public class UserManagement extends javax.swing.JFrame {

    /**
     * Creates new form UserManagement
     */
    public UserManagement() {
        initComponents();
        loadEmployees();
        loadSuppliers();
    }

    public void loadEmployees() {
        try {
            // Search user table from database
            ResultSet resultSet = MYSQL.execute("SELECT * FROM `user` "
                    + "INNER JOIN `role` ON `user`.`role_id` = `role`.`role_id` "
                    + "INNER JOIN `status` ON `user`.`status_id` = `status`.`status_id` ");

            // Load data to table
            DefaultTableModel model = (DefaultTableModel) jTableStaff.getModel();
            model.setRowCount(0);

            // Get data to table
            while (resultSet.next()) {
                Vector<String> vector1 = new Vector<>();

                vector1.add(resultSet.getString("user_id"));
                vector1.add(resultSet.getString("name"));
                vector1.add(resultSet.getString("role.name"));
                vector1.add(resultSet.getString("status.status"));

                model.addRow(vector1);
            }

            // Set model after adding all rows
            jTableStaff.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void loadSuppliers() {
        try {
            // Search user table from database
            ResultSet resultSet = MYSQL.execute("SELECT * FROM `supplier` "
                    + "INNER JOIN `company` ON `supplier`.`company_id` = `company`.`company_id`");

            // Load data to table
            DefaultTableModel model = (DefaultTableModel) jTableSupliers.getModel();
            model.setRowCount(0);

            // Get data to table
            while (resultSet.next()) {
                Vector<String> vector1 = new Vector<>();

                vector1.add(resultSet.getString("supplier_id")); // Assuming supplier table has 'supplier_id' column
                vector1.add(resultSet.getString("name")); // Assuming supplier table has 'name' column
                vector1.add(resultSet.getString("company.name")); // Assuming company table has 'name' column
                vector1.add(resultSet.getString("mobile")); // Assuming supplier table has 'mobile' column

                model.addRow(vector1);
            }

            // Set model after adding all rows
            jTableSupliers.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelDashboard = new javax.swing.JLabel();
        jLabelSystemconfiguration = new javax.swing.JLabel();
        jLabelLogsAudit = new javax.swing.JLabel();
        jLabelLogOut = new javax.swing.JLabel();
        jPanelCurrent = new javax.swing.JPanel();
        jLabelUserManagement = new javax.swing.JLabel();
        jPaneluser = new javax.swing.JPanel();
        jLabelUseImg = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelUserId = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jPanelScreen = new javax.swing.JPanel();
        jScrollPaneTool = new javax.swing.JScrollPane();
        jPanelTool = new javax.swing.JPanel();
        jButtonResivation = new javax.swing.JButton();
        jButtonHousekeep = new javax.swing.JButton();
        jButtonRestuarantUi = new javax.swing.JButton();
        jButtonGuestUi = new javax.swing.JButton();
        jButtonMaintenanceUi = new javax.swing.JButton();
        jButtonFinancialUi = new javax.swing.JButton();
        jButtonMarketingUi = new javax.swing.JButton();
        jPanelEmployees = new javax.swing.JPanel();
        jScrollPaneTableStaff = new javax.swing.JScrollPane();
        jTableStaff = new javax.swing.JTable();
        jTextFieldSearchStaff = new javax.swing.JTextField();
        jLabelSearch = new javax.swing.JLabel();
        jButtonClearEmployees = new javax.swing.JButton();
        jButtonUserDetails = new javax.swing.JButton();
        jLabelEmployees = new javax.swing.JLabel();
        jPanelSupliers = new javax.swing.JPanel();
        jLabelSearch4 = new javax.swing.JLabel();
        jLabelSupliers = new javax.swing.JLabel();
        jTextFieldSearchSuplier1 = new javax.swing.JTextField();
        jButtonClearSupliers = new javax.swing.JButton();
        jButtonSupliersCompanies = new javax.swing.JButton();
        jLabelTotalCompanies = new javax.swing.JLabel();
        jLabelCountCompanies = new javax.swing.JLabel();
        jScrollPaneTableSupliers1 = new javax.swing.JScrollPane();
        jTableSupliers = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        jPanelMenu.setBackground(new java.awt.Color(83, 66, 54));
        jPanelMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelMenu.setPreferredSize(new java.awt.Dimension(200, 500));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N

        jLabelDashboard.setBackground(new java.awt.Color(83, 66, 54));
        jLabelDashboard.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabelDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDashboard.setText("Dashboard");
        jLabelDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDashboardMouseClicked(evt);
            }
        });

        jLabelSystemconfiguration.setBackground(new java.awt.Color(83, 66, 54));
        jLabelSystemconfiguration.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabelSystemconfiguration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSystemconfiguration.setText("System Configuration");
        jLabelSystemconfiguration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSystemconfiguration.setPreferredSize(null);
        jLabelSystemconfiguration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSystemconfigurationMouseClicked(evt);
            }
        });

        jLabelLogsAudit.setBackground(new java.awt.Color(83, 66, 54));
        jLabelLogsAudit.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabelLogsAudit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogsAudit.setText("Logs/Audit Trails");
        jLabelLogsAudit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLogsAudit.setPreferredSize(null);
        jLabelLogsAudit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogsAuditMouseClicked(evt);
            }
        });

        jLabelLogOut.setBackground(new java.awt.Color(83, 66, 54));
        jLabelLogOut.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabelLogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogOut.setText("Log Out");
        jLabelLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLogOut.setPreferredSize(null);

        jPanelCurrent.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCurrent.setPreferredSize(new java.awt.Dimension(199, 32));

        jLabelUserManagement.setBackground(new java.awt.Color(83, 66, 54));
        jLabelUserManagement.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabelUserManagement.setForeground(new java.awt.Color(83, 66, 54));
        jLabelUserManagement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserManagement.setText("User Management ");
        jLabelUserManagement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelUserManagement.setPreferredSize(null);
        jLabelUserManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUserManagementMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelCurrentLayout = new javax.swing.GroupLayout(jPanelCurrent);
        jPanelCurrent.setLayout(jPanelCurrentLayout);
        jPanelCurrentLayout.setHorizontalGroup(
            jPanelCurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
            .addGroup(jPanelCurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCurrentLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelUserManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelCurrentLayout.setVerticalGroup(
            jPanelCurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelCurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCurrentLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jLabelUserManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPaneluser.setBackground(new java.awt.Color(83, 66, 54));
        jPaneluser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPaneluser.setPreferredSize(new java.awt.Dimension(199, 72));

        jLabelUseImg.setBackground(new java.awt.Color(83, 66, 54));
        jLabelUseImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/user.png"))); // NOI18N

        jLabelId.setBackground(new java.awt.Color(83, 66, 54));
        jLabelId.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabelId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelId.setText("ID     : ");
        jLabelId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelUserName.setBackground(new java.awt.Color(83, 66, 54));
        jLabelUserName.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabelUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserName.setText("Shehara");
        jLabelUserName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelUserId.setBackground(new java.awt.Color(83, 66, 54));
        jLabelUserId.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabelUserId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserId.setText("RS0001");
        jLabelUserId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelName.setBackground(new java.awt.Color(83, 66, 54));
        jLabelName.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelName.setText("Name:");
        jLabelName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPaneluserLayout = new javax.swing.GroupLayout(jPaneluser);
        jPaneluser.setLayout(jPaneluserLayout);
        jPaneluserLayout.setHorizontalGroup(
            jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneluserLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabelUseImg)
                .addGap(10, 10, 10)
                .addGroup(jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneluserLayout.createSequentialGroup()
                        .addComponent(jLabelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUserId))
                    .addGroup(jPaneluserLayout.createSequentialGroup()
                        .addComponent(jLabelName)
                        .addGap(3, 3, 3)
                        .addComponent(jLabelUserName)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPaneluserLayout.setVerticalGroup(
            jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneluserLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUseImg)
                    .addGroup(jPaneluserLayout.createSequentialGroup()
                        .addGroup(jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUserId))
                        .addGap(4, 4, 4)
                        .addGroup(jPaneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelName)
                            .addComponent(jLabelUserName)))))
        );

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMenuLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabelLogo))
                            .addComponent(jPaneluser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelSystemconfiguration, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                .addComponent(jLabelLogOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                .addComponent(jLabelLogsAudit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanelCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addComponent(jLabelLogo)
                .addGap(30, 30, 30)
                .addComponent(jLabelDashboard)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanelCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabelSystemconfiguration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabelLogsAudit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabelLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPaneluser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanelMenu, java.awt.BorderLayout.LINE_START);

        jPanelScreen.setBackground(new java.awt.Color(255, 255, 255));
        jPanelScreen.setDoubleBuffered(false);

        jScrollPaneTool.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPaneTool.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPaneTool.setPreferredSize(new java.awt.Dimension(1008, 85));

        jPanelTool.setBackground(new java.awt.Color(83, 66, 54));
        jPanelTool.setFocusTraversalPolicyProvider(true);

        jButtonResivation.setBackground(new java.awt.Color(155, 117, 1));
        jButtonResivation.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonResivation.setForeground(new java.awt.Color(255, 255, 255));
        jButtonResivation.setText("Reservation ");
        jButtonResivation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(83, 66, 54), new java.awt.Color(83, 66, 54), new java.awt.Color(83, 66, 54), new java.awt.Color(83, 66, 54)));
        jButtonResivation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonResivation.setFocusable(false);
        jButtonResivation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonResivation.setPreferredSize(new java.awt.Dimension(128, 40));
        jButtonResivation.setSelected(true);
        jButtonResivation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResivationActionPerformed(evt);
            }
        });

        jButtonHousekeep.setBackground(new java.awt.Color(155, 117, 1));
        jButtonHousekeep.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonHousekeep.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHousekeep.setText("Housekeeping");
        jButtonHousekeep.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(83, 66, 54), new java.awt.Color(83, 66, 54), new java.awt.Color(83, 66, 54), new java.awt.Color(83, 66, 54)));
        jButtonHousekeep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonHousekeep.setFocusable(false);
        jButtonHousekeep.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonHousekeep.setPreferredSize(new java.awt.Dimension(128, 40));
        jButtonHousekeep.setSelected(true);
        jButtonHousekeep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHousekeepActionPerformed(evt);
            }
        });

        jButtonRestuarantUi.setBackground(new java.awt.Color(155, 117, 1));
        jButtonRestuarantUi.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonRestuarantUi.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRestuarantUi.setText("Restuarant");
        jButtonRestuarantUi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(83, 66, 54), new java.awt.Color(83, 66, 54), new java.awt.Color(83, 66, 54), new java.awt.Color(83, 66, 54)));
        jButtonRestuarantUi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRestuarantUi.setFocusable(false);
        jButtonRestuarantUi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRestuarantUi.setPreferredSize(new java.awt.Dimension(128, 40));
        jButtonRestuarantUi.setSelected(true);
        jButtonRestuarantUi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestuarantUiActionPerformed(evt);
            }
        });

        jButtonGuestUi.setBackground(new java.awt.Color(155, 117, 1));
        jButtonGuestUi.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonGuestUi.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuestUi.setText("Guest Services ");
        jButtonGuestUi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(83, 66, 54), new java.awt.Color(83, 66, 54), new java.awt.Color(83, 66, 54), new java.awt.Color(83, 66, 54)));
        jButtonGuestUi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGuestUi.setFocusable(false);
        jButtonGuestUi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGuestUi.setPreferredSize(new java.awt.Dimension(128, 40));
        jButtonGuestUi.setSelected(true);
        jButtonGuestUi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuestUiActionPerformed(evt);
            }
        });

        jButtonMaintenanceUi.setBackground(new java.awt.Color(155, 117, 1));
        jButtonMaintenanceUi.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonMaintenanceUi.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMaintenanceUi.setText("Maintenance");
        jButtonMaintenanceUi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(83, 66, 54), new java.awt.Color(83, 66, 54), new java.awt.Color(83, 66, 54), new java.awt.Color(83, 66, 54)));
        jButtonMaintenanceUi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMaintenanceUi.setFocusable(false);
        jButtonMaintenanceUi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonMaintenanceUi.setPreferredSize(new java.awt.Dimension(128, 40));
        jButtonMaintenanceUi.setSelected(true);
        jButtonMaintenanceUi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMaintenanceUiActionPerformed(evt);
            }
        });

        jButtonFinancialUi.setBackground(new java.awt.Color(155, 117, 1));
        jButtonFinancialUi.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonFinancialUi.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFinancialUi.setText("Financial");
        jButtonFinancialUi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(83, 66, 54), new java.awt.Color(83, 66, 54), new java.awt.Color(83, 66, 54), new java.awt.Color(83, 66, 54)));
        jButtonFinancialUi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFinancialUi.setFocusable(false);
        jButtonFinancialUi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFinancialUi.setPreferredSize(new java.awt.Dimension(128, 40));
        jButtonFinancialUi.setSelected(true);

        jButtonMarketingUi.setBackground(new java.awt.Color(155, 117, 1));
        jButtonMarketingUi.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonMarketingUi.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMarketingUi.setText("Marketing");
        jButtonMarketingUi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(83, 66, 54), new java.awt.Color(83, 66, 54), new java.awt.Color(83, 66, 54), new java.awt.Color(83, 66, 54)));
        jButtonMarketingUi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMarketingUi.setFocusable(false);
        jButtonMarketingUi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonMarketingUi.setPreferredSize(new java.awt.Dimension(128, 40));
        jButtonMarketingUi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonMarketingUi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMarketingUiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelToolLayout = new javax.swing.GroupLayout(jPanelTool);
        jPanelTool.setLayout(jPanelToolLayout);
        jPanelToolLayout.setHorizontalGroup(
            jPanelToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelToolLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonResivation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButtonHousekeep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButtonRestuarantUi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButtonGuestUi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButtonMaintenanceUi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButtonFinancialUi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButtonMarketingUi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanelToolLayout.setVerticalGroup(
            jPanelToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonResivation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHousekeep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRestuarantUi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGuestUi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMaintenanceUi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFinancialUi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMarketingUi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPaneTool.setViewportView(jPanelTool);

        jPanelEmployees.setBackground(new java.awt.Color(221, 217, 214));
        jPanelEmployees.setPreferredSize(new java.awt.Dimension(286, 392));

        jScrollPaneTableStaff.setBackground(new java.awt.Color(83, 66, 54));
        jScrollPaneTableStaff.setAutoscrolls(true);
        jScrollPaneTableStaff.setPreferredSize(new java.awt.Dimension(262, 292));

        jTableStaff.setAutoCreateRowSorter(true);
        jTableStaff.setBackground(new java.awt.Color(199, 189, 177));
        jTableStaff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableStaff.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTableStaff.setForeground(new java.awt.Color(83, 66, 54));
        jTableStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Name", "Role", "Status (On/Off)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableStaff.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableStaff.setGridColor(new java.awt.Color(255, 255, 255));
        jTableStaff.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTableStaff.setSelectionForeground(new java.awt.Color(155, 117, 1));
        jTableStaff.getTableHeader().setReorderingAllowed(false);
        jScrollPaneTableStaff.setViewportView(jTableStaff);

        jTextFieldSearchStaff.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextFieldSearchStaff.setForeground(new java.awt.Color(83, 66, 54));
        jTextFieldSearchStaff.setText(" Search User ID");
        jTextFieldSearchStaff.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(155, 117, 1)));
        jTextFieldSearchStaff.setDisabledTextColor(new java.awt.Color(221, 217, 214));
        jTextFieldSearchStaff.setPreferredSize(new java.awt.Dimension(91, 30));
        jTextFieldSearchStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchStaffActionPerformed(evt);
            }
        });

        jLabelSearch.setBackground(new java.awt.Color(83, 66, 54));
        jLabelSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.png"))); // NOI18N

        jButtonClearEmployees.setBackground(new java.awt.Color(155, 117, 1));
        jButtonClearEmployees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/clear.png"))); // NOI18N
        jButtonClearEmployees.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        jButtonClearEmployees.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClearEmployees.setPreferredSize(new java.awt.Dimension(25, 25));
        jButtonClearEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearEmployeesActionPerformed(evt);
            }
        });

        jButtonUserDetails.setBackground(new java.awt.Color(83, 66, 54));
        jButtonUserDetails.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonUserDetails.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUserDetails.setText("All Users");
        jButtonUserDetails.setToolTipText("");
        jButtonUserDetails.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jButtonUserDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUserDetails.setPreferredSize(new java.awt.Dimension(70, 30));
        jButtonUserDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonUserDetailsMouseClicked(evt);
            }
        });

        jLabelEmployees.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEmployees.setFont(new java.awt.Font("SansSerif", 3, 25)); // NOI18N
        jLabelEmployees.setForeground(new java.awt.Color(83, 66, 54));
        jLabelEmployees.setText("Employees");
        jLabelEmployees.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(83, 66, 55)));
        jLabelEmployees.setPreferredSize(new java.awt.Dimension(132, 34));

        javax.swing.GroupLayout jPanelEmployeesLayout = new javax.swing.GroupLayout(jPanelEmployees);
        jPanelEmployees.setLayout(jPanelEmployeesLayout);
        jPanelEmployeesLayout.setHorizontalGroup(
            jPanelEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmployeesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanelEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEmployeesLayout.createSequentialGroup()
                        .addComponent(jLabelSearch)
                        .addGap(2, 2, 2)
                        .addComponent(jTextFieldSearchStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButtonClearEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonUserDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPaneTableStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelEmployeesLayout.setVerticalGroup(
            jPanelEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmployeesLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabelEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanelEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSearchStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonClearEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUserDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTableStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelSupliers.setBackground(new java.awt.Color(221, 217, 214));
        jPanelSupliers.setPreferredSize(new java.awt.Dimension(293, 392));

        jLabelSearch4.setBackground(new java.awt.Color(83, 66, 54));
        jLabelSearch4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.png"))); // NOI18N

        jLabelSupliers.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSupliers.setFont(new java.awt.Font("SansSerif", 3, 25)); // NOI18N
        jLabelSupliers.setForeground(new java.awt.Color(83, 66, 54));
        jLabelSupliers.setText("Supliers & Companies");
        jLabelSupliers.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(83, 66, 54)));
        jLabelSupliers.setPreferredSize(new java.awt.Dimension(269, 34));

        jTextFieldSearchSuplier1.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextFieldSearchSuplier1.setForeground(new java.awt.Color(83, 66, 54));
        jTextFieldSearchSuplier1.setText(" Search NIC");
        jTextFieldSearchSuplier1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(155, 117, 1)));
        jTextFieldSearchSuplier1.setDisabledTextColor(new java.awt.Color(221, 217, 214));
        jTextFieldSearchSuplier1.setPreferredSize(new java.awt.Dimension(129, 25));
        jTextFieldSearchSuplier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchSuplier1ActionPerformed(evt);
            }
        });

        jButtonClearSupliers.setBackground(new java.awt.Color(155, 117, 1));
        jButtonClearSupliers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/clear.png"))); // NOI18N
        jButtonClearSupliers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        jButtonClearSupliers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClearSupliers.setPreferredSize(new java.awt.Dimension(25, 25));
        jButtonClearSupliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearSupliersActionPerformed(evt);
            }
        });

        jButtonSupliersCompanies.setBackground(new java.awt.Color(83, 66, 54));
        jButtonSupliersCompanies.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonSupliersCompanies.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSupliersCompanies.setText("All Supliers & Companies");
        jButtonSupliersCompanies.setToolTipText("");
        jButtonSupliersCompanies.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214), new java.awt.Color(221, 217, 214)));
        jButtonSupliersCompanies.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSupliersCompanies.setPreferredSize(new java.awt.Dimension(193, 30));
        jButtonSupliersCompanies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSupliersCompaniesMouseClicked(evt);
            }
        });
        jButtonSupliersCompanies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupliersCompaniesActionPerformed(evt);
            }
        });

        jLabelTotalCompanies.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabelTotalCompanies.setForeground(new java.awt.Color(83, 66, 54));
        jLabelTotalCompanies.setText("Total Companies :");

        jLabelCountCompanies.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabelCountCompanies.setForeground(new java.awt.Color(155, 117, 1));
        jLabelCountCompanies.setText("45");
        jLabelCountCompanies.setPreferredSize(new java.awt.Dimension(47, 26));

        jScrollPaneTableSupliers1.setBackground(new java.awt.Color(83, 66, 54));
        jScrollPaneTableSupliers1.setAutoscrolls(true);
        jScrollPaneTableSupliers1.setPreferredSize(new java.awt.Dimension(269, 211));

        jTableSupliers.setAutoCreateRowSorter(true);
        jTableSupliers.setBackground(new java.awt.Color(199, 189, 177));
        jTableSupliers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableSupliers.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTableSupliers.setForeground(new java.awt.Color(83, 66, 54));
        jTableSupliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Company", "Mobile", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSupliers.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableSupliers.setGridColor(new java.awt.Color(255, 255, 255));
        jTableSupliers.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTableSupliers.setSelectionForeground(new java.awt.Color(155, 117, 1));
        jTableSupliers.getTableHeader().setReorderingAllowed(false);
        jScrollPaneTableSupliers1.setViewportView(jTableSupliers);
        jTableSupliers.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanelSupliersLayout = new javax.swing.GroupLayout(jPanelSupliers);
        jPanelSupliers.setLayout(jPanelSupliersLayout);
        jPanelSupliersLayout.setHorizontalGroup(
            jPanelSupliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSupliersLayout.createSequentialGroup()
                .addGroup(jPanelSupliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelSupliersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneTableSupliers1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelSupliersLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanelSupliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSupliers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelSupliersLayout.createSequentialGroup()
                                .addComponent(jLabelSearch4)
                                .addGap(0, 0, 0)
                                .addComponent(jTextFieldSearchSuplier1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonClearSupliers, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelSupliersLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSupliersCompanies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelSupliersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTotalCompanies, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCountCompanies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelSupliersLayout.setVerticalGroup(
            jPanelSupliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSupliersLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabelSupliers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButtonSupliersCompanies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSupliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalCompanies, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCountCompanies, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSupliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelSearch4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonClearSupliers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldSearchSuplier1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTableSupliers1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelScreenLayout = new javax.swing.GroupLayout(jPanelScreen);
        jPanelScreen.setLayout(jPanelScreenLayout);
        jPanelScreenLayout.setHorizontalGroup(
            jPanelScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneTool, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanelScreenLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanelEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSupliers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );
        jPanelScreenLayout.setVerticalGroup(
            jPanelScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelScreenLayout.createSequentialGroup()
                .addComponent(jScrollPaneTool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSupliers, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                    .addComponent(jPanelEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        getContentPane().add(jPanelScreen, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(816, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDashboardMouseClicked
        AdminDashboard adminDashboard = new AdminDashboard();//Show the AdminDashboard
        adminDashboard.setVisible(true); // Show the AdminDashboard
        this.setVisible(false); // Close the current UserManagement
    }//GEN-LAST:event_jLabelDashboardMouseClicked

    private void jLabelSystemconfigurationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSystemconfigurationMouseClicked
        SystemConfiguration systemConfiguration = new SystemConfiguration();// Get the new SystemConfiguration
        systemConfiguration.setVisible(true); // Show the new SystemConfiguration
        this.setVisible(false); // Close the current window
    }//GEN-LAST:event_jLabelSystemconfigurationMouseClicked

    private void jLabelLogsAuditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogsAuditMouseClicked
        Logs_Audit Logs_Audit = new Logs_Audit();// Get the new logs&audit
        Logs_Audit.setVisible(true); // Show the new logs&audit
        this.setVisible(false); // Close the current window
    }//GEN-LAST:event_jLabelLogsAuditMouseClicked

    private void jButtonResivationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResivationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonResivationActionPerformed

    private void jButtonHousekeepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHousekeepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHousekeepActionPerformed

    private void jButtonRestuarantUiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestuarantUiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRestuarantUiActionPerformed

    private void jButtonGuestUiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuestUiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuestUiActionPerformed

    private void jButtonMaintenanceUiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMaintenanceUiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMaintenanceUiActionPerformed

    private void jButtonMarketingUiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMarketingUiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMarketingUiActionPerformed

    private void jLabelUserManagementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUserManagementMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelUserManagementMouseClicked

    private void jTextFieldSearchStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchStaffActionPerformed

    private void jButtonClearEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearEmployeesActionPerformed
        jButtonClearEmployees.setText("");
    }//GEN-LAST:event_jButtonClearEmployeesActionPerformed

    private void jButtonUserDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUserDetailsMouseClicked
        UserDetails userDetails = new UserDetails();// Instantiate the new UserDetails window
        userDetails.setVisible(true); // Show the UserDetails window
        this.setVisible(false);    // Hide the current window
    }//GEN-LAST:event_jButtonUserDetailsMouseClicked

    private void jTextFieldSearchSuplier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchSuplier1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchSuplier1ActionPerformed

    private void jButtonClearSupliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearSupliersActionPerformed
        jButtonClearSupliers.setText("");
    }//GEN-LAST:event_jButtonClearSupliersActionPerformed

    private void jButtonSupliersCompaniesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSupliersCompaniesMouseClicked
        Supliers_companies supliers_companies = new Supliers_companies();
        supliers_companies.setVisible(true); // Show the UserDetails window
        this.setVisible(false);    // Hide the current window
    }//GEN-LAST:event_jButtonSupliersCompaniesMouseClicked

    private void jButtonSupliersCompaniesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupliersCompaniesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSupliersCompaniesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClearEmployees;
    private javax.swing.JButton jButtonClearSupliers;
    private javax.swing.JButton jButtonFinancialUi;
    private javax.swing.JButton jButtonGuestUi;
    private javax.swing.JButton jButtonHousekeep;
    private javax.swing.JButton jButtonMaintenanceUi;
    private javax.swing.JButton jButtonMarketingUi;
    private javax.swing.JButton jButtonResivation;
    private javax.swing.JButton jButtonRestuarantUi;
    private javax.swing.JButton jButtonSupliersCompanies;
    private javax.swing.JButton jButtonUserDetails;
    private javax.swing.JLabel jLabelCountCompanies;
    private javax.swing.JLabel jLabelDashboard;
    private javax.swing.JLabel jLabelEmployees;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelLogOut;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelLogsAudit;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelSearch4;
    private javax.swing.JLabel jLabelSupliers;
    private javax.swing.JLabel jLabelSystemconfiguration;
    private javax.swing.JLabel jLabelTotalCompanies;
    private javax.swing.JLabel jLabelUseImg;
    private javax.swing.JLabel jLabelUserId;
    private javax.swing.JLabel jLabelUserManagement;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanelCurrent;
    private javax.swing.JPanel jPanelEmployees;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelScreen;
    private javax.swing.JPanel jPanelSupliers;
    private javax.swing.JPanel jPanelTool;
    private javax.swing.JPanel jPaneluser;
    private javax.swing.JScrollPane jScrollPaneTableStaff;
    private javax.swing.JScrollPane jScrollPaneTableSupliers1;
    private javax.swing.JScrollPane jScrollPaneTool;
    private javax.swing.JTable jTableStaff;
    private javax.swing.JTable jTableSupliers;
    private javax.swing.JTextField jTextFieldSearchStaff;
    private javax.swing.JTextField jTextFieldSearchSuplier1;
    // End of variables declaration//GEN-END:variables
}
